import type {Marker,PreviewState,Scenario,Report,ReportMarkerValue,ServerZone} from './model';
import {reportInputSignature} from './policy';
const rows:[string,string,string,number,string,[number,number],[number,number],number[],string][]=[
 ['apob','ApoB','Cardiovascular',78,'mg/dL',[45,90],[0,150],[99,88,78],'Una medida del número de partículas que transportan colesterol y pueden contribuir al riesgo cardiovascular.'],
 ['hscrp','hsCRP','Inflamación',2.1,'mg/L',[0,1],[0,5],[2.8,2.4,2.1],'Un marcador sensible de inflamación. Una infección reciente o ejercicio intenso pueden influir en una lectura.'],
 ['hba1c','HbA1c','Metabolismo',5.2,'%', [4,5.6],[3,8],[5.5,5.3,5.2],'Refleja la exposición promedio a la glucosa durante los últimos meses.'],
 ['insulin','Insulina en ayunas','Metabolismo',8.4,'µIU/mL',[2,10],[0,25],[12.1,10.3,8.4],'Ayuda a contextualizar cómo responde el cuerpo a la glucosa. El ayuno y el resto del panel importan.'],
 ['triglycerides','Triglicéridos','Cardiovascular',101,'mg/dL',[40,150],[0,250],[138,118,101],'Grasas que circulan en la sangre y se interpretan junto con el resto del perfil lipídico.'],
 ['hdl','HDL','Cardiovascular',58,'mg/dL',[40,80],[0,110],[49,54,58],'Transporta colesterol. Una sola cifra no resume el riesgo cardiovascular.'],
 ['ldl','LDL','Cardiovascular',103,'mg/dL',[40,100],[0,200],[122,115,103],'Una fracción del colesterol que se considera junto con ApoB y el contexto personal.'],
 ['ferritin','Ferritina','Nutrición',64,'ng/mL',[30,150],[0,300],[47,55,64],'Refleja reservas de hierro y también puede cambiar por inflamación.'],
 ['vitamin-d','Vitamina D','Nutrición',28,'ng/mL',[30,60],[0,80],[21,24,28],'Un marcador del estado de vitamina D. Su interpretación depende del contexto individual.'],
 ['b12','Vitamina B12','Nutrición',480,'pg/mL',[300,700],[0,1000],[420,451,480],'Participa en funciones del sistema nervioso y la formación de células sanguíneas.'],
 ['tsh','TSH','Tiroides',1.8,'mIU/L',[0.5,3],[0,6],[2.2,2,1.8],'Una señal hormonal que ayuda a valorar la función tiroidea junto con otros datos.'],
 ['alt','ALT','Hígado',24,'U/L',[7,35],[0,80],[32,28,24],'Enzima que aporta contexto sobre el hígado. También puede responder a ejercicio y medicamentos.'],
 ['creatinine','Creatinina','Riñón',0.9,'mg/dL',[0.6,1.2],[0,2],[0.95,0.92,0.9],'Se interpreta con edad, masa muscular y otras medidas de función renal.'],
 ['uric-acid','Ácido úrico','Metabolismo',4.8,'mg/dL',[3,6],[0,10],[5.6,5.2,4.8],'Producto del metabolismo cuya lectura depende de alimentación, función renal y otros factores.'],
 ['ggt','GGT','Hígado',20,'U/L',[5,40],[0,90],[28,24,20],'Enzima que contribuye a contextualizar el estado del hígado y las vías biliares.']
];
export const sampleMarkers:Marker[]=rows.map(([key,name,category,value,unit,range,domain,history,description])=>({key,name,category,value,unit,range,domain,history,description,status:value<range[0]||value>range[1]?'attention':'optimal',interpretation:'Lectura ilustrativa. Revisa este dato junto con su evolución, el rango del laboratorio y tu contexto. No establece un diagnóstico ni una recomendación individual.'}));
export const statusLabels={es:{optimal:'Óptimo',attention:'Fuera del rango orientativo',action:'Requiere revisión',unknown:'Sin clasificación'},en:{optimal:'Optimal',attention:'Outside illustrative range',action:'Review needed',unknown:'Unclassified'}};

/** Fictional editorial readings for design review. No patient record or AI response is used. */
function readingFixture(month:'marzo'|'junio'):Report {
 const june=month==='junio',id=`demo-${month}`;
 const report:Report={id,version:1,date:june?'2026-06-12':'2026-03-12',name:june?'Tu lectura de junio':'Tu lectura de marzo',source:june?'kit':'upload',status:'ready',markerKeys:sampleMarkers.map(m=>m.key),contextComplete:true,biologicalAge:june?29:30,longevityScore:june?82:78,biological_age_comprehensive:null,bio_age_method:null,bio_age_n_markers:null,bio_age_applied_spanish_calibration:null,longevity_grade:null};
 report.markerValues=Object.fromEntries(sampleMarkers.map(marker=>{
  const value=june?marker.value:marker.history[1];
  const zone:ServerZone=value<marker.range[0]?'below_optimal':value>marker.range[1]?'above_optimal':'optimal';
  const stance=zone==='optimal'?['dentro del intervalo ilustrativo','within the illustrative interval']:zone==='below_optimal'?['por debajo del intervalo ilustrativo','below the illustrative interval']:['por encima del intervalo ilustrativo','above the illustrative interval'];
  const facts:Record<string,[string,string]>={
   apob:['Se lee junto con LDL y los otros lípidos: estas piezas describen aspectos distintos del mismo perfil.','Read it alongside LDL and the other lipids: they describe different aspects of the same profile.'],
   hscrp:['El ejemplo no permite atribuir esta cifra a una infección. Falta una respuesta conocida sobre enfermedad cerca de la muestra.','This example cannot attribute the value to an infection. Illness near the sample date remains unknown.'],
   hba1c:['Aporta perspectiva al panel metabólico junto con la insulina; no equivale a una medición de glucosa de ese día.','It adds perspective to the metabolic panel alongside insulin; it is not a glucose reading from that day.'],
   insulin:['El dato pertenece a esta muestra. La duración del ayuno es una pieza de contexto que debe mantenerse junto al resultado.','This value belongs to this sample. Fasting duration is context that should remain attached to the result.'],
   triglycerides:['Forma parte de la lectura conjunta de ApoB, LDL y HDL. No resume por sí solo el perfil cardiovascular.','It belongs with ApoB, LDL and HDL in the lipid profile. It does not summarize cardiovascular health alone.'],
   hdl:['Acompaña al resto de los lípidos. Su posición en un intervalo no sustituye una lectura del conjunto.','It accompanies the other lipids. Its place in an interval does not replace reading the whole panel.'],
   ldl:['En este informe, LDL y ApoB no tienen la misma clasificación. Esa diferencia merece una explicación conjunta, no dos conclusiones aisladas.','In this report, LDL and ApoB have different classifications. That difference needs a joint explanation rather than two isolated conclusions.'],
   ferritin:['La cifra se conserva junto a hsCRP y los otros datos disponibles; no se atribuye su valor a una causa concreta.','The value stays alongside hsCRP and the other available results; no specific cause is assigned to it.'],
   'vitamin-d':['Se muestra como una pieza de la lectura nutricional. El ejemplo no establece una pauta de suplementos.','It is one part of the nutritional reading. This example does not establish a supplement regimen.'],
   b12:['Se lee como parte del conjunto nutricional. La cifra sola no cuenta toda la historia de alimentación o absorción.','It is read as part of the nutritional picture. The number alone does not tell the whole story of diet or absorption.'],
   tsh:['Es una señal dentro del contexto tiroideo, no una conclusión sobre toda la función tiroidea.','It is one signal within thyroid context, not a conclusion about overall thyroid function.'],
   alt:['En el ejemplo, ALT y GGT comparten la clasificación dentro del intervalo. El historial y el contexto siguen siendo partes distintas de su lectura.','In this example, ALT and GGT are both within their intervals. History and context remain separate parts of the reading.'],
   creatinine:['La cifra necesita acompañarse de edad, masa muscular y otros datos; aquí no se calcula una conclusión renal adicional.','The value needs age, muscle mass and other data alongside it; no additional kidney conclusion is calculated here.'],
   'uric-acid':['Aporta otra pieza al conjunto metabólico. No se infiere una causa ni una acción a partir de esta cifra aislada.','It adds another piece to the metabolic picture. No cause or action is inferred from this isolated value.'],
   ggt:['Se presenta junto a ALT en el informe. Una clasificación dentro del intervalo no equivale a una evaluación completa del hígado.','It is presented alongside ALT. Being within an interval is not a complete assessment of liver health.'],
  };
  const [es,en]=facts[marker.key];
  const simpleEs=`${marker.name}: ${value} ${marker.unit}, ${stance[0]} en ${month}.`;
  const simpleEn=`${marker.name}: ${value} ${marker.unit}, ${stance[1]} in ${june?'June':'March'}.`;
  const result:ReportMarkerValue={value,unit:marker.unit,zone,optimal_low:marker.range[0],optimal_high:marker.range[1],normal_low:null,normal_high:null,interpretation_es:`${simpleEs} ${es}`,interpretation:`${simpleEn} ${en}`,
   interpretationVariants:{simple:{interpretation_es:simpleEs,interpretation:simpleEn},balanced:{interpretation_es:`${simpleEs} ${es}`,interpretation:`${simpleEn} ${en}`},advanced:{interpretation_es:`${simpleEs} ${es} La clasificación y los intervalos pertenecen exclusivamente a este caso ficticio.`,interpretation:`${simpleEn} ${en} Classification and intervals belong exclusively to this fictional case.`}}};
  return [marker.key,result];
 }));
 const simpleEs=june?'Metabolismo y enzimas hepáticas comparten una lectura dentro de los intervalos del ejemplo. El perfil cardiovascular tiene un matiz: ApoB está dentro, mientras LDL aparece por encima. hsCRP y vitamina D son las otras piezas que necesitan contexto.':'Marzo es el punto de partida de este archivo. El panel metabólico es mixto: HbA1c está dentro del intervalo del ejemplo y la insulina aparece por encima. LDL, hsCRP y vitamina D completan los valores señalados.';
 const simpleEn=june?'Metabolic markers and liver enzymes share a reading within the example intervals. The cardiovascular picture has a nuance: ApoB is within range while LDL is above it. hsCRP and vitamin D are the other pieces needing context.':'March is the starting point of this archive. The metabolic picture is mixed: HbA1c is within the example interval while insulin is above it. LDL, hsCRP and vitamin D complete the flagged readings.';
 const extraEs=june?'ApoB (78 mg/dL) y LDL (103 mg/dL) cuentan partes diferentes del perfil lipídico; se leen juntos. hsCRP (2,1 mg/L) necesita el contexto del día de la muestra, que aquí no permite confirmar una enfermedad reciente. La vitamina D (28 ng/mL) queda por debajo del intervalo ilustrativo. Los valores nutricionales, tiroideos y renales restantes completan el panorama, sin convertir una clasificación en un diagnóstico.':'En marzo, insulina (10,3 µIU/mL), LDL (115 mg/dL) y hsCRP (2,4 mg/L) están por encima de sus intervalos ilustrativos; vitamina D (24 ng/mL), por debajo. ApoB (88 mg/dL) y HbA1c (5,3 %) permanecen dentro. El archivo todavía no aporta una lectura anterior comparable para este informe.';
 const extraEn=june?'ApoB (78 mg/dL) and LDL (103 mg/dL) describe different parts of the lipid profile and should be read together. hsCRP (2.1 mg/L) needs sample-day context; this example cannot confirm recent illness. Vitamin D (28 ng/mL) is below its illustrative interval. The remaining nutritional, thyroid and kidney values complete the picture without turning a classification into a diagnosis.':'In March, insulin (10.3 µIU/mL), LDL (115 mg/dL) and hsCRP (2.4 mg/L) are above their illustrative intervals; vitamin D (24 ng/mL) is below. ApoB (88 mg/dL) and HbA1c (5.3%) remain within. This report has no earlier comparable reading in the archive.';
 report.summary_narrative_es=`${simpleEs}\n\n${extraEs}`;
 report.summary_narrative=`${simpleEn}\n\n${extraEn}`;
 report.narrativeVariants={simple:{summary_narrative_es:simpleEs,summary_narrative:simpleEn},balanced:{summary_narrative_es:report.summary_narrative_es,summary_narrative:report.summary_narrative},advanced:{summary_narrative_es:`${report.summary_narrative_es}\n\nLos intervalos son ilustrativos. No se ha aplicado el contexto guardado ni se ha inferido causalidad. Las lecturas de distinto origen se mantienen separadas.`,summary_narrative:`${report.summary_narrative}\n\nIntervals are illustrative. Saved context has not been applied and causation has not been inferred. Readings from different sources are kept separate.`}};
 report.context={version:1,versionId:`${id}-context-1`,confirmedAt:`${report.date}T12:00:00Z`,durable:{},transient:{currently_ill:'unknown',fasted:june?'eight_to_twelve':'unknown',last_workout:'unknown'}};
 report.actionSteps=[
  {id:`${id}-context`,lab_result_id:id,priority:1,category:'context',title:'Complete the sample-day picture',title_es:'Completa la historia de ese día',description:'Confirm what is known about illness, exercise and fasting near this sample. Unknown is a valid answer.',description_es:'Revisa qué sabes sobre enfermedad, ejercicio y ayuno cerca de esta muestra. No recordarlo también es una respuesta válida.',related_biomarker_keys:['hscrp','insulin'],status:'pending'},
  {id:`${id}-lipids`,lab_result_id:id,priority:2,category:'reading',title:'Read the lipid profile together',title_es:'Lee el perfil lipídico en conjunto',description:'Explore ApoB and LDL side by side, with their distinct units, intervals and explanations.',description_es:'Explora ApoB y LDL juntos, con sus valores, intervalos y explicaciones diferenciadas.',related_biomarker_keys:['apob','ldl'],status:'pending'},
 ];
 report.reading={reportId:id,reportVersion:1,inputSignature:reportInputSignature(report),status:'ready',literacy:'balanced',contextApplied:false,contextVersionId:report.context.versionId,origin:'editorial_fixture'};
 return report;
}

export function createFixture(scenario:Scenario='ready'):PreviewState {
 const current=readingFixture('junio');
 if(scenario==='processing'||scenario==='context'||scenario==='error'){current.status=scenario==='context'?'pending_context':scenario;current.contextComplete=scenario!=='context';current.biologicalAge=null;current.longevityScore=null;current.reading={...current.reading!,status:'processing'};}
 return {version:1,session:true,scenario,plan:scenario==='new'?'free':'quarterly',subscriptionStatus:'active',profile:{firstName:'Alex',current_ba:null,current_ba_method:null,current_ba_n_labs_averaged:null,current_ba_window_months:null,current_ba_n_markers_used:null,current_ba_computed_at:null,literacy:'balanced',birthYear:'1992',dateOfBirth:'1992-04-18',address:'Calle de Ejemplo, 12',postalCode:'28001',city:'Madrid',notifications:{email:true,results:true,reminders:true,marketing:false},wearableConnected:true,healthConsent:true,aiConsent:false},wearableObservations:scenario==='new'?[]:[{date:'2026-06-06',source:'Apple Health · importación de ejemplo',hrv_ms:46,resting_hr_bpm:59,sleep_hours:7.1,respiratory_rate:null,recovery_score:null,steps:5800},{date:'2026-06-07',source:'Apple Health · importación de ejemplo',hrv_ms:null,resting_hr_bpm:60,sleep_hours:null,respiratory_rate:null,recovery_score:null,steps:7300},{date:'2026-06-08',source:'Apple Health · importación de ejemplo',hrv_ms:50,resting_hr_bpm:58,sleep_hours:8.1,respiratory_rate:14,recovery_score:null,steps:null},{date:'2026-06-09',source:'Apple Health · importación de ejemplo',hrv_ms:47,resting_hr_bpm:null,sleep_hours:7.6,respiratory_rate:null,recovery_score:null,steps:8100},{date:'2026-06-10',source:'Apple Health · importación de ejemplo',hrv_ms:48,resting_hr_bpm:58,sleep_hours:7.4,respiratory_rate:null,steps:6200},{date:'2026-06-11',source:'Apple Health · importación de ejemplo',hrv_ms:null,resting_hr_bpm:57,sleep_hours:7.8,respiratory_rate:null,steps:null}],reports:scenario==='new'||scenario==='kit'?[]:[current,readingFixture('marzo')],markers:sampleMarkers.map(m=>({...m,history:[...m.history]})),totalUploadsUsed:scenario==='new'||scenario==='kit'?0:1,kitCycle:scenario==='new'?undefined:scenario==='kit'?{id:'demo-cycle-active',status:'shipped',dueDate:'2026-09-21',trackingCode:'EJEMPLO-DHL-001',extractionAt:null,version:1,reportId:null}:{id:'demo-cycle-june',status:scenario==='ready'?'completed':'processing',dueDate:'2026-06-12',trackingCode:'EJEMPLO-DHL-000',extractionAt:'2026-06-12T08:30:00Z',version:1,reportId:'demo-junio'},kitStep:scenario==='kit'?2:4,kitReportId:scenario==='new'||scenario==='kit'?null:'demo-junio',onboarded:scenario!=='new',chat:[],deletionStatus:'none',lastAction:''};
}
export const dateLabel=(value:string)=>new Intl.DateTimeFormat('es',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(value));
export const numberLabel=(value:number)=>new Intl.NumberFormat('es',{maximumFractionDigits:2}).format(value);
