import type {Profile,Report,Locale} from '@/lib/preview/model';
import {estimateProvenance} from './dashboard-observations';

const copy={es:{title:'La procedencia de las estimaciones.',report:'Este informe',rolling:'Lectura conjunta de varios informes',none:'No consta',method:'Método',markers:'Biomarcadores utilizados',calibration:'Calibración española aplicada',grade:'Grado de longevidad',comprehensive:'Edad Comprehensive',labs:'Informes incluidos',window:'Ventana',computed:'Último cálculo',months:'meses',years:'años',noCalibration:'Ninguna registrada',note:'El ejemplo no contiene metadatos de cálculo confirmados. Un campo vacío no se completa con datos de otro informe.',rollingNote:'Esta lectura pertenece al perfil y puede reunir varias fechas. Se mantiene separada de la estimación de este informe.'},en:{title:'Where the estimates come from.',report:'This report',rolling:'Combined reading from several reports',none:'Not provided',method:'Method',markers:'Biomarkers used',calibration:'Spanish calibration applied',grade:'Longevity grade',comprehensive:'Comprehensive age',labs:'Reports included',window:'Window',computed:'Last calculation',months:'months',years:'years',noCalibration:'None recorded',note:'This example has no confirmed calculation metadata. Missing fields are never filled from another report.',rollingNote:'This reading belongs to the profile and may combine several dates. It remains separate from this report’s estimate.'}} as const;
export function EstimateMetadata({report,profile,locale='es'}:{report:Report;profile:Profile;locale?:Locale}){
 const e=estimateProvenance(report,profile),c=copy[locale],number=(n:number|null)=>n===null?c.none:new Intl.NumberFormat(locale,{maximumFractionDigits:2}).format(n);
 const row=(label:string,value:string)=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>;
 return <section className="dashboard-estimate-provenance" data-estimate-report={report.id}><h3>{c.title}</h3><div><article><h4>{c.report}</h4><dl>{row(c.method,e.method||c.none)}{row(c.markers,number(e.markerCount))}{row(c.comprehensive,e.comprehensiveAge===null?c.none:`${number(e.comprehensiveAge)} ${c.years}`)}{row(c.calibration,e.calibration===null?c.none:e.calibration.length?e.calibration.join(', '):c.noCalibration)}{row(c.grade,e.grade||c.none)}</dl>{!e.method&&<p>{c.note}</p>}</article><article><h4>{c.rolling}</h4><p className="dashboard-rolling-age" data-profile-rolling-age>{e.rolling.value===null?c.none:`${number(e.rolling.value)} ${c.years}`}</p><dl>{row(c.method,e.rolling.method||c.none)}{row(c.labs,number(e.rolling.labs))}{row(c.window,e.rolling.months===null?c.none:`${e.rolling.months} ${c.months}`)}{row(c.markers,number(e.rolling.markers))}{row(c.computed,e.rolling.computedAt?new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(e.rolling.computedAt)):c.none)}</dl><p>{c.rollingNote}</p></article></div></section>;
}
