'use client';
import {useId} from 'react';
import type {Literacy,Locale} from '@/lib/preview/model';
import {dateLabel} from '@/lib/preview/fixtures';
import {selectReportNarrative,type ExecutiveStory} from './dashboard-reading';
import {paragraphsForReading,segmentsWithEntities} from './summary-format';
import './report-summary.css';

const copy={es:{eyebrow:'LA HISTORIA DE TUS RESULTADOS',title:<>Tu última lectura,<br/>en contexto.</>,depth:'Profundidad',levels:{simple:'Esencial',balanced:'Con contexto',advanced:'En detalle'},whole:'UNA LECTURA COMPLETA',first:<>Primero el conjunto.<br/>Después, cada dato.</>,owned:<>El texto pertenece<br/>a este informe.</>,sample:'Texto de demostración del informe. Los intervalos y resultados de este ejemplo no son personales.',end:<>El conjunto es el punto de partida.<br/><strong>Ahora puedes acercarte a cada resultado.</strong></>,explore:'Explorar los datos',time:'min de lectura',state:'Estado del informe',language:'Este texto está disponible en inglés.',critical:'La clasificación del informe señala un valor crítico. Revisa el resultado completo; no se reduce a una puntuación general.',states:{missing:['SIN TEXTO DISPONIBLE','Este informe aún no incluye un resumen.','La ausencia de texto no cambia los resultados.'],variant:['VERSIÓN NO DISPONIBLE','Este nivel todavía no tiene un texto propio.','Elige otro nivel disponible.'],pending:['EN PREPARACIÓN','Estamos preparando tu lectura.','La interpretación se mostrará cuando termine el procesamiento del informe.'],stale:['PENDIENTE DE ACTUALIZAR','Los datos cambiaron. La lectura debe actualizarse.','La versión anterior no se presenta como una interpretación de los resultados actuales.'],error:['NO SE PUDO CARGAR','No pudimos recuperar el resumen.','La ausencia de texto no cambia los resultados.']}},en:{eyebrow:'THE STORY OF YOUR RESULTS',title:<>Your latest reading,<br/>in context.</>,depth:'Depth',levels:{simple:'Essential',balanced:'With context',advanced:'In detail'},whole:'THE COMPLETE READING',first:<>The whole picture first.<br/>Then, each result.</>,owned:<>This text belongs<br/>to this report.</>,sample:'Demonstration report text. These example intervals and results are not personal.',end:<>The whole picture is the starting point.<br/><strong>Now explore each result.</strong></>,explore:'Explore the results',time:'min read',state:'Report status',language:'This text is available in English.',critical:'The report classifies a result as critical. Review the complete result; it is not reduced to an overall score.',states:{missing:['NO TEXT AVAILABLE','This report does not yet include a summary.','Missing text does not change the results.'],variant:['VERSION UNAVAILABLE','This level does not have its own text yet.','Choose another available level.'],pending:['IN PREPARATION','Your reading is being prepared.','The interpretation will be shown once report processing finishes.'],stale:['AWAITING UPDATE','The data changed. This reading needs updating.','The previous version is not presented as an interpretation of current results.'],error:['UNABLE TO LOAD','The summary could not be retrieved.','Missing text does not change the results.']}}} as const;

export default function ReportSummary({story,locale,level,onLevel}:{story:ExecutiveStory;locale:Locale;level:Literacy;onLevel:(level:Literacy)=>void}){
 const id=useId(),c=copy[locale],narrative=selectReportNarrative(story.report,locale,level);
 const paragraphs=paragraphsForReading(narrative.text,narrative.language);
 const variantMissing=narrative.state==='missing'&&level!==story.report.reading?.literacy&&story.report.reading?.status==='ready';
 const state=narrative.state==='ready'?null:c.states[variantMissing?'variant':narrative.state];
 const critical=story.evidence.some(item=>item.zone==='critical_high'||item.zone==='critical_low');
 let available=6;const seen=new Set<string>();
 const names=[...new Set(story.evidence.flatMap(item=>[item.name,item.key]))];
 const rendered=paragraphs.map((text,index)=>{
  const segments=segmentsWithEntities(text,names.filter(name=>!seen.has(name.toLowerCase())),Math.min(2,available));
  for(const part of segments)if(part.emphasis){available--;seen.add(part.text.toLowerCase());}
  return <p key={index} data-source-order={index+1} data-long={text.length>800}>{segments.map((part,i)=>part.emphasis?<strong key={i}>{part.text}</strong>:part.text)}</p>;
 });
 const dots=[];for(let y=6;y<100;y+=7)for(let x=6;x<100;x+=7){const distance=Math.hypot(x-50,y-50);if(distance<=44&&distance>=14)dots.push(<circle key={`${x}-${y}`} cx={x} cy={y} r={Math.max(.4,2.6-(distance-14)/13)} opacity=".5"/>);}
 return <article className="report-summary" id="dashboard-reading" aria-labelledby={`${id}-title`} data-report-id={story.reportId} data-report-version={story.version} data-narrative-state={narrative.state}>
  <header className="summary-header"><div className="summary-index"><span>02</span><p>{c.eyebrow}</p></div><div className="summary-title"><div className="summary-source"><time dateTime={story.date}>{dateLabel(story.date)}</time><span>{narrative.text?`${Math.max(1,Math.ceil(narrative.text.split(/\s+/).length/200))} ${c.time}`:c.state}</span></div><h2 id={`${id}-title`}>{c.title}</h2></div><div className="summary-stamp" aria-hidden="true"><svg viewBox="0 0 100 100">{dots}</svg></div></header>
  <div className="summary-main"><aside className="summary-margin"><p className="eyebrow">{c.whole}</p><p>{c.first}</p><div className="summary-progress" aria-hidden="true"/><span className="summary-margin-note">{c.owned}</span></aside><div className="summary-column"><div className="summary-level"><span>{c.depth}</span><div role="group" aria-label={c.depth}>{(['simple','balanced','advanced'] as const).map(item=><button type="button" key={item} aria-pressed={level===item} disabled={['stale','pending','error'].includes(narrative.state)} onClick={()=>onLevel(item)}>{c.levels[item]}</button>)}</div></div><div className="summary-narrative" lang={narrative.language} data-panel-narrative={story.reportId} data-entering="true" key={`${story.reportId}-${story.version}-${level}-${narrative.state}`}>{state?<><p className="state-label">{state[0]}</p><h3 className="state-title">{state[1]}</h3><p className="state-text">{state[2]}</p></>:rendered}</div>{narrative.text&&narrative.language!==locale&&<p className="summary-language">{c.language}</p>}{critical&&<p className="summary-critical" role="note">{c.critical}</p>}<p className="summary-narrative-caption">{c.sample}</p>{!state&&<footer className="summary-end"><span className="summary-end-dot" aria-hidden="true"/><p>{c.end}</p><a href="#dashboard-biomarkers">{c.explore}<span aria-hidden="true">↗</span></a></footer>}</div></div>
 </article>;
}
