'use client';

import {useId,useState} from 'react';
import type {PreviewState,Locale} from '@/lib/preview/model';
import {dateLabel,numberLabel} from '@/lib/preview/fixtures';
import {selectWearableObservations} from './dashboard-reading';
import {wearableSeries,wearableChartPoints,wearableMetrics,wearableMetricLabel,type WearableMetric} from './dashboard-observations';

const copy={es:{eyebrow:'ENTRE LECTURAS / EJEMPLO',title:'Tu día, registrado.',metric:'Qué quieres observar',source:'Fuente del registro',all:'Todas las fuentes',missing:'Sin dato',date:'Fecha',value:'Valor',raw:'Ver los registros',import:'Revisar importación',disconnected:'No hay una importación activa en este ejemplo.',empty:'La importación no contiene registros con fecha disponibles.',metricEmpty:'Esta medida no figura en los registros seleccionados.',note:'Observaciones ficticias importadas. Los huecos se conservan; no se calculan correlaciones ni se atribuyen cambios en tus análisis.',scale:'Escala visual, no un intervalo de salud.',previous:'Registro anterior',next:'Registro siguiente',chart:'Registros por fecha',sample:'DATOS FICTICIOS'},en:{eyebrow:'BETWEEN REPORTS / EXAMPLE',title:'Your day, recorded.',metric:'What to observe',source:'Record source',all:'All sources',missing:'No data',date:'Date',value:'Value',raw:'View records',import:'Review import',disconnected:'This example has no active import.',empty:'The import has no dated records available.',metricEmpty:'This measure is absent from the selected records.',note:'Fictional imported observations. Gaps are preserved; no correlations or causes for lab changes are calculated.',scale:'Visual scale, not a health interval.',previous:'Previous record',next:'Next record',chart:'Records by date',sample:'FICTIONAL DATA'}} as const;

export function WearableObservations({state,locale='es'}:{state:PreviewState;locale?:Locale}){
 const id=useId().replaceAll(':',''),c=copy[locale];const [metric,setMetric]=useState<WearableMetric>('sleep_hours'),[source,setSource]=useState('all'),[selected,setSelected]=useState<string|null>(null);
 const available=selectWearableObservations(state),sources=[...new Set(available.map(row=>row.source))];
 const currentSource=source==='all'||sources.includes(source)?source:'all',rows=wearableSeries(state,metric,currentSource),chart=wearableChartPoints(rows),index=selected?rows.findIndex(row=>row.id===selected):-1;
 const at=index>=0?index:rows.length-1,row=rows[at],metadata=wearableMetrics[metric];
 const date=(value:string)=>locale==='es'?dateLabel(value):new Intl.DateTimeFormat('en',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(value));
 const unit=locale==='en'&&metric==='steps'?'steps':locale==='en'&&metric==='resting_hr_bpm'?'bpm':metadata.unit;
 return <section className="dashboard-wearable" aria-labelledby={`${id}-title`}><div className="dashboard-wearable-heading"><p className="dashboard-mini-label">{c.eyebrow}</p><h2 id={`${id}-title`}>{c.title}</h2></div>
 {!state.profile.wearableConnected?<p className="dashboard-wearable-empty">{c.disconnected}</p>:!rows.length&&available.length===0?<p className="dashboard-wearable-empty">{c.empty}</p>:<>
 <div className="dashboard-wearable-controls"><label><span>{c.metric}</span><select value={metric} onChange={event=>{setMetric(event.target.value as WearableMetric);setSelected(null)}}>{(Object.keys(wearableMetrics) as WearableMetric[]).map(key=><option value={key} key={key}>{wearableMetricLabel(key,locale)}</option>)}</select></label>{sources.length>1&&<label><span>{c.source}</span><select value={currentSource} onChange={event=>{setSource(event.target.value);setSelected(null)}}><option value="all">{c.all}</option>{sources.map(value=><option key={value}>{value}</option>)}</select></label>}</div>
 <div className="dashboard-wearable-glass eva-glass eva-glass-sage"><div className="dashboard-wearable-readout" aria-live="polite"><p>{wearableMetricLabel(metric,locale)}</p><strong>{row?.value!==null&&row?.value!==undefined?numberLabel(row.value):c.missing}<small>{row?.value!==null&&row?.value!==undefined?unit:''}</small></strong>{row&&<span><time dateTime={row.date}>{date(row.date)}</time> · {row.source}</span>}</div>
 <div className="dashboard-wearable-chart"><svg viewBox="0 0 360 155" role="img" aria-labelledby={`${id}-chart-title`}><title id={`${id}-chart-title`}>{`${c.chart}: ${wearableMetricLabel(metric,locale)}. ${rows.map(item=>`${item.date}, ${item.value===null?c.missing:item.value+' '+unit}, ${item.source}`).join('; ')}`}</title><defs><pattern id={`${id}-dots`} width="9" height="9" patternUnits="userSpaceOnUse"><circle cx="4.5" cy="4.5" r=".6" fill="currentColor" opacity=".16"/></pattern></defs><rect x="12" y="8" width="336" height="125" fill={`url(#${id}-dots)`}/><path d="M12 137H348" stroke="currentColor" opacity=".25"/>{chart.points.map(point=><g key={point.id}>{point.y!==null?<><path d={`M${point.x*3.6} ${point.y*1.55}V137`} stroke="currentColor" opacity=".22" strokeDasharray="1 4"/><circle cx={point.x*3.6} cy={point.y*1.55} r={row?.id===point.id?8:4} stroke="currentColor" fill={row?.id===point.id?'currentColor':'transparent'} strokeWidth="1.3"/></>:<circle cx={point.x*3.6} cy="137" r="3.5" fill="none" stroke="currentColor" strokeDasharray="1 2" opacity=".45"/>}</g>)}</svg>{chart.low===null&&<p>{c.metricEmpty}</p>}</div>
 <div className="dashboard-wearable-navigation"><button type="button" disabled={at<=0} aria-label={c.previous} onClick={()=>setSelected(rows[at-1].id)}>←</button><span>{rows.length?`${at+1} / ${rows.length}`:'0 / 0'}</span><button type="button" disabled={at<0||at>=rows.length-1} aria-label={c.next} onClick={()=>setSelected(rows[at+1].id)}>→</button></div><p className="dashboard-wearable-scale">{c.scale}</p></div>
 <details className="dashboard-wearable-table"><summary>{c.raw}<span aria-hidden="true">+</span></summary><div role="region" aria-label={c.raw} tabIndex={0}><table><caption>{wearableMetricLabel(metric,locale)} · {c.sample}</caption><thead><tr><th>{c.date}</th><th>{c.value}</th><th>{c.source}</th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><th scope="row"><button type="button" aria-pressed={row?.id===item.id} onClick={()=>setSelected(item.id)}>{date(item.date)}</button></th><td>{item.value===null?c.missing:`${numberLabel(item.value)} ${unit}`}</td><td>{item.source}</td></tr>)}</tbody></table></div></details>
 </>}
 <p className="dashboard-wearable-note">{c.note}</p><a className="dashboard-wearable-link" href="/es/profile#dispositivos">{c.import} <span aria-hidden="true">↗</span></a></section>;
}
