'use client';
import {Player,type PlayerRef} from '@remotion/player';
import {useRef,useState} from 'react';
import {AnalogType} from './AnalogType';
import {SignalFilm} from './SignalFilm';
import {Slider} from '@/components/ui/slider';
import {SIGNAL_DURATION,signalStops,signalLabels} from '@/lib/analog-motion';
export function AnalogSpecimen(){
 const player=useRef<PlayerRef>(null),[frame,setFrame]=useState(0);
 const seek=(n:number)=>{const f=Math.max(0,Math.min(SIGNAL_DURATION-1,Math.round(n)));player.current?.seekTo(f);setFrame(f)};
 return <section id="analog-signal" className="analog-specimen"><h2>01c / Analog Signal — tipografía y puntos</h2><div className="analog-specimen-intro"><div className="analog-type-sample"><AnalogType text="salud." width={600} height={250} frame={frame} style={{width:'100%',height:'auto',aspectRatio:'12 / 5'}}/></div><div><h3>Una señal<br/><em>con carácter.</em></h3><p>La silueta serif se construye con pequeñas celdas luminosas. Dentro, letras que cambian con el avance de la escena. Los datos mantienen la matriz original, con una trama más fina y espacio visible entre cada círculo. Los puntos se encienden y apagan por separado, en pasos breves, como un antiguo panel electrónico.</p><p>La imagen mantiene su suavidad. La tipografía aporta precisión, con el contraste de una pantalla analógica.</p></div></div><div className="lab-player"><Player ref={player} component={SignalFilm} compositionWidth={1440} compositionHeight={900} durationInFrames={SIGNAL_DURATION} fps={30} controls={false} autoPlay={false} clickToPlay={false} spaceKeyToPlayOrPause={false} doubleClickToFullscreen={false} allowFullscreen={false} style={{width:'100%'}}/></div><div className="timeline"><label id="analog-timeline-label">Señal {String(frame).padStart(3,'0')} / 360</label><Slider aria-labelledby="analog-timeline-label" value={[frame]} onValueChange={v=>seek(Array.isArray(v)?v[0]:v)} min={0} max={360} step={1}/></div><div className="scene-buttons">{signalLabels.map((label,i)=><button key={label} onClick={()=>seek(signalStops[i])}>{label}</button>)}</div><p className="lab-note">Movimiento ligado al scroll, reversible y sin destellos. El cuerpo de texto y las acciones conservan una tipografía continua.</p><div className="analog-reference-links"><a href="https://savee.com/i/uBs8ZE0/" target="_blank" rel="noreferrer">Referencia de movimiento · SAVEE</a><a href="/review/analog-signal.md">Uso del componente</a><a href="/art/reference-analog-letters.png">Referencia tipográfica</a><a href="/#una-senal">Ver en la experiencia</a></div></section>
}
