'use client';

import {useEffect,useMemo,useRef,useState} from 'react';
import {usePreview} from '@/components/preview/PreviewProvider';
import {AppPageHeader,AsyncState,EmptyState,StatusIndicator,SourceTag} from '@/components/preview/AppPrimitives';
import {DotNumber} from '@/components/story/DotNumber';
import {canReadReport,hasPaidAccess,reportReadiness} from '@/lib/preview/policy';
import {dateLabel,numberLabel} from '@/lib/preview/fixtures';
import type {Marker,MarkerStatus,Report,ServerZone} from '@/lib/preview/model';

import {dashboardMarkerForReport,selectMarkerInterpretation,zoneLabels} from '../dashboard/dashboard-reading';
import {ReportNarrative} from './ReportNarrative';
import {BiomarkerHistory} from './BiomarkerHistory';
import {previewHistoryObservations} from './preview-history';
import {biomarkerHistory,historyDirectionLabel} from '../../../lib/labs/biomarker-history';

type StatusFilter='all'|MarkerStatus;
type ReadingView='range'|'change';
type Reading=Marker&{readingValue:number|null;previousValue:number|null;previousDate?:string;readingStatus:MarkerStatus;rangeComparable:boolean;zone:ServerZone};

export const labsCopy={es:{
  eyebrow:'ANÁLISIS / TU HISTORIAL', title:'Tus resultados, por fecha.', intro:'Elige un informe para consultar sus valores y compararlos con otras fechas.',
  archive:'Ver archivo', upload:'Añadir resultados', kit:'Explorar mi kit', loading:'Preparando tu espacio de resultados…',
  access:{title:'Vuelve a tu espacio de salud.',body:'Entra en la cuenta de ejemplo para explorar tus lecturas.',action:'Entrar a la vista previa',consentTitle:'Primero, tu consentimiento.',consentBody:'El acceso a los resultados requiere tu consentimiento para el tratamiento de datos de salud. Puedes revisarlo en tu perfil.',consentAction:'Revisar consentimiento'},
  empty:{title:'Aquí empieza tu primera lectura.',body:'Puedes reunir una analítica que ya tengas o explorar el recorrido de tu primer kit. Tus resultados aparecerán aquí cuando estén listos.',kitTitle:'Tu próxima lectura está en camino.',kitBody:'Sigue el estado de tu kit. Cuando el informe esté listo, podrás explorar sus biomarcadores desde aquí.'},
  missing:{title:'Este informe no está disponible.',body:'El enlace no corresponde a una lectura disponible en esta cuenta de ejemplo.',action:'Volver a mis análisis',archivedTitle:'Esta lectura está en el archivo.',archivedBody:'Puedes consultar y gestionar tus lecturas archivadas desde el archivo de análisis.'},
  picker:{label:'Seleccionar un informe',title:'Informes',source:{kit:'Recogida con kit',upload:'Analítica subida'},statuses:{ready:'Lista',processing:'En proceso',pending_context:'Falta contexto',error:'Revisar archivo',archived:'Archivada'},current:'Lectura actual'},
  gate:{contextTitle:'Completa los datos de esta muestra.',contextBody:'Falta completar la información que acompaña a este informe. Añádela para continuar con la interpretación de ejemplo.',contextAction:'Completar datos de la muestra',processingTitle:'Tu informe está en preparación.',processingBody:'Los valores y las estimaciones se mostrarán cuando termine el procesamiento. Mientras tanto, puedes consultar otra lectura disponible.',errorTitle:'No pudimos completar esta lectura.',errorBody:'Revisa el archivo o vuelve al flujo de subida para preparar el informe de ejemplo. Los resultados incompletos no se muestran.',errorAction:'Revisar la subida',progress:['Archivo recibido','Preparando lectura','Resultados disponibles'],latestReady:'Ver una lectura anterior',contextNote:'El contexto de esta lectura todavía no está completo.'},
  folio:{eyebrow:'INFORME PERSONAL / EJEMPLO',count:'biomarcadores disponibles',date:'Fecha de la lectura',source:'Origen',download:'Descargar ejemplo · CSV',busy:'Preparando descarga…',downloaded:'El archivo de ejemplo está listo para descargar. Solo contiene los datos ficticios de esta lectura.',downloadError:'No se pudo preparar el archivo de ejemplo. Inténtalo de nuevo.',downloadUnavailable:'El informe debe estar listo para poder descargarlo.',full:'Ver biomarcadores',summaryTitle:'Resumen de este informe.',summaryBody:'Los estados resumen los rangos orientativos de este ejemplo. No describen por sí solos tu salud ni sustituyen la interpretación de cada resultado.',labels:{optimal:'Óptimos',attention:'Fuera del rango orientativo',action:'Requieren revisión',unknown:'Sin clasificación'},summaryNote:'Selecciona un estado para recorrer sus biomarcadores.',critical:'Hay resultados marcados para revisión. Consulta su contexto y la orientación de un profesional sanitario antes de tomar decisiones sobre tu salud.'},
  estimates:{eyebrow:'ESTIMACIONES DEL EJEMPLO',age:'Edad biológica estimada',ageUnit:'años',score:'Puntuación de longevidad',scoreUnit:'de 100',unavailable:'No disponible o pendiente de actualizar',ageBody:'Una estimación basada en los datos disponibles; no equivale a un diagnóstico ni a años de vida ganados.',scoreBody:'Una lectura complementaria de los biomarcadores. Su significado depende de la metodología y del contexto.',link:'Cómo se calculan',lockedTitle:'Más contexto con tu plan.',lockedBody:'La edad biológica estimada y la puntuación de longevidad se muestran cuando tu plan y los datos de la lectura lo permiten.',lockedAction:'Explorar planes'},
  panel:{eyebrow:'EL INFORME, BIOMARCADOR A BIOMARCADOR',title:'Todos los valores.',description:'Busca un valor, filtra por sistema o abre su explicación. Todas las cifras corresponden a la lectura seleccionada.',search:'Buscar biomarcador',placeholder:'ApoB, vitamina D, tiroides…',category:'Sistema',allCategories:'Todos los sistemas',filterLabel:'Filtrar por estado',filters:[{id:'all' as StatusFilter,label:'Todos'},{id:'attention' as StatusFilter,label:'Atención'},{id:'action' as StatusFilter,label:'Revisión'},{id:'optimal' as StatusFilter,label:'Óptimos'},{id:'unknown' as StatusFilter,label:'Sin clasificar'}],views:[{id:'range' as ReadingView,label:'Rangos'},{id:'change' as ReadingView,label:'Cambio entre lecturas'}],viewLabel:'Vista de los resultados',range:'Rango orientativo',rangeDescription:'El tramo sombreado representa el rango orientativo del ejemplo.',value:'Resultado',difference:'Cambio entre fechas',noPrevious:'Sin lectura anterior disponible',noValue:'Sin dato en esta lectura',noChange:'Sin cambio',details:'Qué significa',open:'Abrir biomarcador',readingHelp:'Cómo leer esta cifra',context:'Ver el contexto de esta lectura',resultCount:'{count} de {total} biomarcadores',clear:'Limpiar filtros',noResults:'No hay biomarcadores con esos filtros.',noResultsBody:'Prueba con otro nombre, cambia el sistema o vuelve a mostrar todos los resultados.',unitMismatch:'El informe no aporta un intervalo comparable para esta unidad. No se asigna uno de otra lectura.',markerMissing:'Algunos biomarcadores del informe todavía no tienen un valor disponible.'},
  focus:{eyebrow:'RESULTADO SELECCIONADO',title:'Un valor, en detalle.',body:'Elige un biomarcador de este informe.',choose:'Biomarcador en primer plano',date:'Fecha de la muestra',reference:'Rango orientativo del ejemplo',open:'Explorar este biomarcador',note:'El rango es ilustrativo. Para una lectura clínica, se utiliza el rango validado del laboratorio y tu contexto.'},
  next:{eyebrow:'PARA DAR EL SIGUIENTE PASO',title:'La cifra es el comienzo.',contextTitle:'Añade tu contexto.',contextBody:'El ayuno, una enfermedad reciente o tus hábitos pueden ayudar a interpretar una lectura. Revisa la información asociada a este informe.',contextAction:'Revisar contexto',aiTitle:'Pregunta sobre tus resultados.',aiBody:'Explora cómo EVA AI explica los biomarcadores y las tendencias. Las respuestas de esta vista previa son ejemplos educativos.',aiAction:'Abrir EVA AI',aiLocked:'Explorar EVA AI con un plan',note:'Información educativa con datos ficticios. No establece un diagnóstico ni una recomendación individual.'},
  csv:{notice:'EVA · Informe de ejemplo · Datos ficticios',report:'Informe',date:'Fecha',source:'Origen',header:['Biomarcador','Sistema','Valor','Unidad','Rango inferior ilustrativo','Rango superior ilustrativo','Estado'],noValue:'Sin dato',scope:'Exportación de la lectura seleccionada. No contiene datos clínicos reales.'},
  changeNote:'El cambio muestra la diferencia entre las lecturas disponibles. Su dirección no implica, por sí sola, una mejora o un empeoramiento de la salud.',
}};

function Arrow({down=false}:{down?:boolean}){return <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true" style={down?{transform:'rotate(90deg)'}:undefined}><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" strokeWidth="1.3"/></svg>}
const finite=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
const normalize=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const reportPath=(id:string)=>`/es/labs/${encodeURIComponent(id)}`;
const readableDate=(date:string)=>{try{return dateLabel(date)}catch{return date}};

export function readingsForReport(markers:Marker[],report:Report):Reading[]{
 return report.markerKeys.flatMap(key=>{const reading=dashboardMarkerForReport({markers},report,key);return reading?[{...reading,readingValue:finite(reading.value)?reading.value:null,previousValue:null,readingStatus:reading.status}]:[]});
}

export function previousComparableReport(markers:Marker[],reports:Report[],report:Report,healthConsent=true):Report|undefined {
  if(!canReadReport(report,healthConsent))return undefined;
  const currentReadings=readingsForReport(markers,report);
  return [...reports].sort((a,b)=>b.date.localeCompare(a.date)).find(candidate=>candidate.date<report.date&&candidate.source===report.source&&canReadReport(candidate,healthConsent)&&readingsForReport(markers,candidate).some(prior=>prior.readingValue!==null&&currentReadings.some(current=>current.key===prior.key&&current.readingValue!==null&&current.unit===prior.unit)));
}

function ReferenceTrack({marker}:{marker:Reading}){
  if(!marker.rangeComparable)return <span className="labs-no-previous">{labsCopy.es.panel.unitMismatch}</span>;
  if(marker.readingStatus==='unknown')return <span className="labs-no-previous">Sin referencia utilizable para esta lectura</span>;
  const domainSpan=marker.domain[1]-marker.domain[0]||1;
  const percentage=(value:number)=>Math.max(0,Math.min(100,(value-marker.domain[0])/domainSpan*100));
  return <div className="labs-reference"><div className="labs-reference-track" aria-hidden="true"><span className="labs-reference-domain"/><i style={{left:`${percentage(marker.range[0])}%`,width:`${percentage(marker.range[1])-percentage(marker.range[0])}%`}}/>{marker.readingValue!==null&&<b data-status={marker.readingStatus} style={{left:`${percentage(marker.readingValue)}%`}}/>}</div><span>{numberLabel(marker.range[0])}–{numberLabel(marker.range[1])} <small>{marker.unit}</small></span></div>
}

function ChangeTrack({marker,previousDate,currentDate}:{marker:Reading;previousDate?:string;currentDate:string}){
  const c=labsCopy.es.panel;
  if(marker.previousValue===null||marker.readingValue===null||!previousDate)return <span className="labs-no-previous">{c.noPrevious}</span>;
  const difference=marker.readingValue-marker.previousValue;
  return <div className="labs-change-values"><span aria-label={`${c.difference}: ${difference>0?'+':''}${numberLabel(difference)} ${marker.unit}`}>{difference===0?c.noChange:`${difference>0?'+':''}${numberLabel(difference)} ${marker.unit}`}</span><dl><div><dt>{readableDate(previousDate)}</dt><dd>{numberLabel(marker.previousValue)} {marker.unit}</dd></div><div><dt>{readableDate(currentDate)}</dt><dd>{numberLabel(marker.readingValue)} {marker.unit}</dd></div></dl></div>;
}

function ReportPicker({reports,current}:{reports:Report[];current:Report}){
  const c=labsCopy.es.picker;
  return <nav className="labs-report-picker" aria-label={c.label}><label htmlFor="labs-report-select">{c.title}</label><select id="labs-report-select" value={current.id} onChange={event=>window.location.assign(reportPath(event.target.value))}>{reports.filter(report=>report.status!=='archived').map(report=><option key={report.id} value={report.id}>{readableDate(report.date)} · {report.name} · {reportReadiness(report)==='pending_context'?c.statuses.pending_context:c.statuses[report.status]}</option>)}</select></nav>;
}

function PendingReport({report,reports}:{report:Report;reports:Report[]}){
  const c=labsCopy.es.gate;
  const needsContext=report.status==='pending_context'||(report.status==='ready'&&!report.contextComplete);
  const failed=report.status==='error';
  const older=reports.find(item=>item.id!==report.id&&item.status==='ready'&&item.contextComplete);
  return <section className={`labs-pending ${failed?'is-error':''}`} aria-labelledby="labs-pending-title"><div className="labs-pending-art" aria-hidden="true"><span/><span/><span/><div>{Array.from({length:24},(_,i)=><i key={i}/>)}</div></div><div className="labs-pending-copy"><p className="eva-kicker">{readableDate(report.date)}</p><h2 id="labs-pending-title">{needsContext?c.contextTitle:failed?c.errorTitle:c.processingTitle}</h2><p>{needsContext?c.contextBody:failed?c.errorBody:c.processingBody}</p>{!needsContext&&!failed&&<ol className="labs-processing-steps" aria-label={c.processingTitle}>{c.progress.map((label,i)=><li key={label} aria-current={i===1?'step':undefined}><i aria-hidden="true"/>{label}</li>)}</ol>}<div className="labs-inline-actions">{needsContext&&<a className="labs-button" href={`${reportPath(report.id)}/context`}>{c.contextAction}<Arrow/></a>}{failed&&<a className="labs-button" href={`/es/upload?report=${encodeURIComponent(report.id)}`}>{c.errorAction}<Arrow/></a>}{older&&<a className="labs-text-link" href={reportPath(older.id)}>{c.latestReady}<Arrow/></a>}</div></div></section>
}

function csvCell(value:unknown){const text=String(value??'');const safe=/^[=+@-]/.test(text)?`'${text}`:text;return `"${safe.replace(/"/g,'""')}"`}

export default function LabsPage({reportId}:{reportId?:string}){
  const c=labsCopy.es;
  const {state,request,hydrated}=usePreview();
  const [focusedKey,setFocusedKey]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[status,setStatus]=useState<StatusFilter>('all'),[view,setView]=useState<ReadingView>('range'),[downloading,setDownloading]=useState(false),[downloadNote,setDownloadNote]=useState(''),[downloadFailed,setDownloadFailed]=useState(false);
  const reports=useMemo(()=>[...state.reports].sort((a,b)=>b.date.localeCompare(a.date)),[state.reports]);
  const report=reportId?reports.find(item=>item.id===reportId):reports.find(item=>item.status!=='archived');
  const readable=Boolean(canReadReport(report,state.profile.healthConsent)&&state.session&&state.deletionStatus!=='completed');
  const exportAccess=useRef({readable,id:report?.id});exportAccess.current={readable,id:report?.id};
  const paid=hasPaidAccess(state);
  const readings=useMemo(()=>readable&&report?readingsForReport(state.markers,report):[],[readable,report,state.markers]);
  const historyObservations=useMemo(()=>report?previewHistoryObservations(state,report):[],[state,report]);
  const historyModels=useMemo(()=>report?readings.map(marker=>({marker,model:biomarkerHistory(historyObservations,marker.key,report.date,report.id)})):[],[historyObservations,readings,report]);
  const availableReadings=useMemo(()=>historyModels.map(({marker,model})=>{const prior=model.direction!=='insufficient'?model.points.at(-2):undefined;return {...marker,previousValue:prior?.value??null,previousDate:prior?.date}}),[historyModels]);
  const focusHistory=(key:string)=>{setFocusedKey(key);document.getElementById('labs-focus-title')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})};
  const focused=availableReadings.find(marker=>marker.key===focusedKey)||availableReadings.find(marker=>marker.readingStatus==='action')||availableReadings.find(marker=>marker.readingStatus==='attention')||availableReadings[0];
  const counts=useMemo(()=>readings.reduce((value,marker)=>({...value,[marker.readingStatus]:value[marker.readingStatus]+1}),{optimal:0,attention:0,action:0,unknown:0}),[readings]);
  const categories=useMemo(()=>Array.from(new Set(readings.map(marker=>marker.category))).sort((a,b)=>a.localeCompare(b,'es')),[readings]);
  const filtered=useMemo(()=>availableReadings.filter(marker=>(status==='all'||marker.readingStatus===status)&&(category==='all'||marker.category===category)&&(!query.trim()||normalize(`${marker.name} ${marker.key} ${marker.category}`).includes(normalize(query)))),[availableReadings,query,category,status]);
  const groups=useMemo(()=>categories.map(name=>({name,items:filtered.filter(marker=>marker.category===name)})).filter(group=>group.items.length),[categories,filtered]);
  useEffect(()=>{setFocusedKey('');setQuery('');setCategory('all');setStatus('all');setView('range');setDownloadNote('')},[report?.id]);
  const clearFilters=()=>{setQuery('');setCategory('all');setStatus('all')};
  const selectStatus=(next:StatusFilter)=>{setStatus(next);document.getElementById('labs-results-heading')?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})};

  async function downloadReport(){
    if(!report||!readable){setDownloadFailed(true);setDownloadNote(c.folio.downloadUnavailable);return}
    setDownloading(true);setDownloadFailed(false);setDownloadNote('');
    try{
      const result=await request('data.export',{reportId:report.id,format:'csv',scope:'fictional-report'});
      if(!result.ok)throw new Error(result.message);
      if(!exportAccess.current.readable||exportAccess.current.id!==report.id)return;
      const rows:unknown[][]=[[c.csv.notice],[c.csv.report,report.name],[c.csv.date,report.date],[c.csv.source,c.picker.source[report.source]],[c.csv.scope],[],c.csv.header,...readings.map(marker=>[marker.name,marker.category,marker.readingValue??c.csv.noValue,marker.unit,marker.rangeComparable?marker.range[0]:c.csv.noValue,marker.rangeComparable?marker.range[1]:c.csv.noValue,zoneLabels.es[marker.zone]])];
      const blob=new Blob(['\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'});
      const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`eva-${report.id.replace(/[^a-z0-9-]/gi,'')}-ejemplo.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setDownloadNote(c.folio.downloaded);
    }catch{setDownloadFailed(true);setDownloadNote(c.folio.downloadError)}finally{setDownloading(false)}
  }

  const header=<AppPageHeader eyebrow={c.eyebrow} title={c.title} description={c.intro} action={<a className="labs-text-link" href="/es/labs/manage">{c.archive}<Arrow/></a>}/>;
  if(!hydrated)return <div className="page-labs">{header}<AsyncState message={c.loading}/></div>;
  if(!state.session||state.deletionStatus==='completed')return <div className="page-labs">{header}<EmptyState title={c.access.title} description={c.access.body}><a className="labs-button" href={`/es/login?redirect=${encodeURIComponent(reportId?reportPath(reportId):'/es/labs')}`}>{c.access.action}<Arrow/></a></EmptyState></div>;
  if(!state.profile.healthConsent)return <div className="page-labs">{header}<EmptyState title={c.access.consentTitle} description={c.access.consentBody}><a className="labs-button" href="/es/profile#consentimientos">{c.access.consentAction}<Arrow/></a></EmptyState></div>;
  if(!report&&reportId)return <div className="page-labs">{header}<EmptyState title={c.missing.title} description={c.missing.body}><a className="labs-button" href="/es/labs">{c.missing.action}<Arrow/></a></EmptyState></div>;
  if(!report)return <div className="page-labs">{header}<EmptyState title={state.scenario==='kit'?c.empty.kitTitle:c.empty.title} description={state.scenario==='kit'?c.empty.kitBody:c.empty.body}><div className="labs-empty-actions"><a className="labs-button" href={state.scenario==='kit'?'/es/book':'/es/upload'}>{state.scenario==='kit'?c.kit:c.upload}<Arrow/></a><a className="labs-text-link" href={state.scenario==='kit'?'/es/upload':'/es/book'}>{state.scenario==='kit'?c.upload:c.kit}<Arrow/></a></div></EmptyState></div>;
  if(report.status==='archived')return <div className="page-labs">{header}<EmptyState title={c.missing.archivedTitle} description={c.missing.archivedBody}><a className="labs-button" href="/es/labs/manage">{c.archive}<Arrow/></a></EmptyState></div>;
  if(reportReadiness(report)==='empty')return <div className="page-labs">{header}<ReportPicker reports={reports} current={report}/><EmptyState title="Este informe aún no contiene valores." description="Puedes consultar otro informe o añadir resultados."><a className="labs-button" href="/es/upload">{c.upload}<Arrow/></a></EmptyState></div>;
  if(!readable)return <div className="page-labs">{header}<ReportPicker reports={reports} current={report}/><PendingReport report={report} reports={reports}/></div>;
  const hasAge=paid&&finite(report.biologicalAge),hasScore=paid&&finite(report.longevityScore);

  return <div className="page-labs">{header}<ReportPicker reports={reports} current={report}/>
    <div className="labs-report-spread">
    <section className="labs-folio" aria-labelledby="labs-folio-title"><div className="labs-folio-masthead"><div><p className="eva-kicker">{c.folio.eyebrow}</p><h2 id="labs-folio-title">{report.name}</h2><p className="labs-report-date">{readableDate(report.date)} · Versión {report.version??1}</p></div><SourceTag>{c.picker.source[report.source]}</SourceTag></div><div className="labs-folio-body"><div className="labs-folio-index"><span>{String(readings.length).padStart(2,'0')}</span><p>{c.folio.count}</p><div className="labs-index-dots" aria-hidden="true">{readings.map(marker=><i key={marker.key} data-status={marker.readingStatus}/>)}</div></div><div className="labs-folio-summary"><h3>{c.folio.summaryTitle}</h3><p>{c.folio.summaryBody}</p><div className="labs-status-summary" role="group" aria-label={c.folio.summaryNote}>{(['optimal','attention','action','unknown'] as MarkerStatus[]).filter(key=>key!=='unknown'||counts.unknown>0).map(key=><button key={key} type="button" onClick={()=>selectStatus(key)} aria-pressed={status===key} data-status={key}><span>{String(counts[key]).padStart(2,'0')}</span><StatusIndicator status={key} label={c.folio.labels[key]}/></button>)}</div></div></div><div className="labs-folio-foot"><a className="labs-text-link" href="#labs-results-heading">{c.folio.full}<Arrow down/></a><button className="labs-text-link" type="button" onClick={downloadReport} disabled={downloading}>{downloading?c.folio.busy:c.folio.download}<Arrow down/></button></div></section>
    {focused&&<section className="labs-focus" aria-labelledby="labs-focus-title"><div className="labs-focus-copy"><p className="eva-kicker">{c.focus.eyebrow}</p><h2 id="labs-focus-title">Tu resultado y su evolución.</h2><label className="labs-focus-select"><span>{c.focus.choose}</span><select value={focused.key} onChange={event=>setFocusedKey(event.target.value)}>{availableReadings.map(marker=><option key={marker.key} value={marker.key}>{marker.name}</option>)}</select></label></div><article className={`labs-focus-capsule eva-glass ${focused.readingStatus==='optimal'?'eva-glass-lilac':'labs-focus-amber'}`} aria-label={`${focused.name}: ${focused.readingValue===null?c.panel.noValue:numberLabel(focused.readingValue)} ${focused.unit}`}><div className="labs-focus-top"><div><p>{focused.category}</p><h3>{focused.name}</h3></div><StatusIndicator status={focused.readingStatus} label={zoneLabels.es[focused.zone]}/></div><div className="labs-focus-value" aria-live="polite">{focused.readingValue===null?<p>{c.panel.noValue}</p>:<><span aria-hidden="true"><DotNumber value={String(focused.readingValue)} calm density="coarse"/></span><span className="labs-visually-hidden">{numberLabel(focused.readingValue)}</span><small>{focused.unit}</small></>}</div><BiomarkerHistory key={report.id+'-'+focused.key} observations={historyObservations} markerKey={focused.key} asOf={report.date} reportId={report.id}/><div className="labs-focus-range"><p>{c.focus.reference}</p><ReferenceTrack marker={focused}/></div><p className="labs-capsule-note">{c.focus.note}</p><div className="labs-focus-date"><span>{c.focus.date}</span><span>{readableDate(report.date)}</span></div><a href={`/es/biomarker/${encodeURIComponent(focused.key)}?report=${encodeURIComponent(report.id)}`} className="labs-focus-link">{c.focus.open}<Arrow/></a></article></section>}

    </div>
    {downloadNote&&<div className={`labs-download-note ${downloadFailed?'is-error':''}`} role={downloadFailed?'alert':'status'}>{downloadNote}</div>}
    {counts.action>0&&<AsyncState error message={c.folio.critical}/>}
    {historyModels.some(item=>item.model.change!==null)&&<section className="labs-history-overview" aria-labelledby="labs-evolution-title"><p className="eva-kicker">LA ÚLTIMA LECTURA, CON PERSPECTIVA</p><h3 id="labs-evolution-title">Qué ha cambiado en tus valores.</h3><p>Estas señales comparan las muestras disponibles hasta este informe. El período se ajusta a cada biomarcador, con un máximo de un año. Selecciona uno para ver sus fechas y su explicación.</p><div className="labs-history-overview-grid">{historyModels.filter(item=>item.model.change!==null).map(({marker,model})=><button key={marker.key} type="button" onClick={()=>focusHistory(marker.key)}><strong>{marker.name}</strong><span>{historyDirectionLabel(model,'es')}</span><small>{model.change!>0?'+':''}{numberLabel(model.change!)} {marker.unit}</small></button>)}</div></section>}
    <ReportNarrative key={`${report.id}-${report.version??1}`} report={report} literacy={state.profile.literacy}/>

    <section className="labs-results" aria-labelledby="labs-results-heading"><div className="labs-results-heading"><p className="eva-kicker">{c.panel.eyebrow}</p><h2 id="labs-results-heading">{c.panel.title}</h2><p>{c.panel.description}</p></div><div className="labs-filters"><label className="labs-search"><span>{c.panel.search}</span><div><svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" strokeWidth="1.3"/><path d="m16 16 5 5" stroke="currentColor" strokeWidth="1.3"/></svg><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.panel.placeholder}/></div></label><label className="labs-category"><span>{c.panel.category}</span><select value={category} onChange={event=>setCategory(event.target.value)}><option value="all">{c.panel.allCategories}</option>{categories.map(name=><option key={name} value={name}>{name}</option>)}</select></label></div><div className="labs-filter-row"><div className="labs-status-filters" role="group" aria-label={c.panel.filterLabel}>{c.panel.filters.map(filter=><button type="button" key={filter.id} aria-pressed={status===filter.id} onClick={()=>setStatus(filter.id)}>{filter.label}<span>{filter.id==='all'?readings.length:counts[filter.id]}</span></button>)}</div><div className="labs-view-toggle" role="group" aria-label={c.panel.viewLabel}>{c.panel.views.map(item=><button key={item.id} type="button" aria-pressed={view===item.id} onClick={()=>setView(item.id)}>{item.label}</button>)}</div></div>{view==='change'&&<p className="labs-comparison-context">Cada biomarcador se compara con su muestra anterior disponible dentro del último año, con la misma unidad.</p>}<div className="labs-result-count"><p role="status" aria-live="polite">{c.panel.resultCount.replace('{count}',String(filtered.length)).replace('{total}',String(readings.length))}</p>{(query||category!=='all'||status!=='all')&&<button type="button" onClick={clearFilters}>{c.panel.clear}</button>}</div>
      {filtered.length===0?<div className="labs-filter-empty"><h3>{c.panel.noResults}</h3><p>{c.panel.noResultsBody}</p><button className="labs-text-link" type="button" onClick={clearFilters}>{c.panel.clear}<Arrow/></button></div>:<div className="labs-marker-groups">{groups.map(group=><section className="labs-marker-group" key={group.name} aria-label={group.name}><div className="labs-category-heading"><h3>{group.name}</h3><span>{String(group.items.length).padStart(2,'0')}</span></div>{group.items.map(marker=><article className="labs-marker-row" key={marker.key}><div className="labs-marker-title"><h4><a href={`/es/biomarker/${encodeURIComponent(marker.key)}?report=${encodeURIComponent(report.id)}`}>{marker.name}</a></h4><StatusIndicator status={marker.readingStatus} label={zoneLabels.es[marker.zone]}/></div><div className="labs-marker-value"><span>{marker.readingValue===null?'—':numberLabel(marker.readingValue)}</span><small>{marker.unit}</small>{marker.readingValue===null&&<span className="labs-missing-value">{c.panel.noValue}</span>}</div><div className="labs-marker-reference"><p>{view==='range'?c.panel.range:c.panel.difference}</p>{view==='range'?<ReferenceTrack marker={marker}/>:<ChangeTrack marker={marker} previousDate={marker.previousDate} currentDate={report.date}/>}</div><details className="labs-marker-details"><summary aria-label={`${c.panel.details}: ${marker.name}`}><span>{c.panel.details}</span><Arrow down/></summary><div><p className="eva-kicker">{c.panel.readingHelp}</p><p>{marker.description}</p><button type="button" className="labs-history-open" onClick={()=>focusHistory(marker.key)}>Ver evolución y contexto<Arrow/></button><p className="labs-interpretation" data-marker-interpretation={marker.key} data-report-id={report.id}>{selectMarkerInterpretation(report,marker.key,'es',state.profile.literacy).text??'Esta lectura todavía no tiene una interpretación específica disponible.'}</p><a className="labs-text-link" href={`/es/biomarker/${encodeURIComponent(marker.key)}?report=${encodeURIComponent(report.id)}`}>{c.panel.open}<Arrow/></a></div></details></article>)}</section>)}</div>}
      <p className="labs-panel-note">{view==='range'?c.panel.rangeDescription:c.changeNote}</p>{readings.length<report.markerKeys.length&&<p className="labs-panel-note">{c.panel.markerMissing}</p>}
    </section>

    <details className="labs-estimate-disclosure"><summary>Estimaciones ilustrativas <span aria-hidden="true">+</span></summary><p>Estas cifras son datos ficticios de la demostración. No representan una evaluación de tu salud.</p>
    <section className="labs-estimates" aria-label={c.estimates.eyebrow}>{paid?<><article><p className="eva-kicker">{c.estimates.age}</p><div className="labs-estimate-number">{hasAge?<><span>{numberLabel(report.biologicalAge!)}</span><small>{c.estimates.ageUnit}</small></>:<p className="labs-estimate-missing">{c.estimates.unavailable}</p>}</div><p>{c.estimates.ageBody}</p></article><article><p className="eva-kicker">{c.estimates.score}</p><div className="labs-estimate-number">{hasScore?<><span>{numberLabel(report.longevityScore!)}</span><small>{c.estimates.scoreUnit}</small></>:<p className="labs-estimate-missing">{c.estimates.unavailable}</p>}</div><p>{c.estimates.scoreBody}</p></article><a className="labs-estimate-method" href="/es/metodologia">{c.estimates.link}<Arrow/></a></>:<div className="labs-estimates-locked"><div><h2>{c.estimates.lockedTitle}</h2><p>{c.estimates.lockedBody}</p></div><a className="labs-text-link" href="/es/pricing">{c.estimates.lockedAction}<Arrow/></a></div>}</section>

    </details>

    <section className="labs-next" aria-labelledby="labs-next-heading"><div><p className="eva-kicker">{c.next.eyebrow}</p><h2 id="labs-next-heading">{c.next.title}</h2></div><div className="labs-next-actions"><article><span className="labs-next-number">01</span><h3>{c.next.contextTitle}</h3><p>{c.next.contextBody}</p><a className="labs-text-link" href={`${reportPath(report.id)}/context`}>{c.next.contextAction}<Arrow/></a></article><article><span className="labs-next-number">02</span><h3>{c.next.aiTitle}</h3><p>{c.next.aiBody}</p><a className="labs-text-link" href={paid?`/es/eva-ai?report=${encodeURIComponent(report.id)}`:'/es/pricing'}>{paid?c.next.aiAction:c.next.aiLocked}<Arrow/></a></article></div><p className="labs-education-note">{c.next.note}</p></section>
  </div>;
}
