'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {betaNext,simulateBetaAccess,simulateBetaSubscribe,type BetaScenario} from './beta-preview';
import './beta-access.css';

export default function BetaPage(){
 const[password,setPassword]=useState(''),[error,setError]=useState(''),[next,setNext]=useState('/es/dashboard'),[scenario,setScenario]=useState<BetaScenario>('normal'),[accessNext,setAccessNext]=useState(''),[email,setEmail]=useState(''),[waitError,setWaitError]=useState(''),[waitDone,setWaitDone]=useState(false),[failWait,setFailWait]=useState(false);
 const seen=useRef(new Set<string>()),emailRef=useRef<HTMLInputElement>(null);
 useEffect(()=>setNext(betaNext(new URLSearchParams(location.search).get('next'))),[]);
 function enter(event:FormEvent){event.preventDefault();const result=simulateBetaAccess({password,next},scenario);if(!result.ok){setError(result.error);return}setError('');setAccessNext(result.next);setPassword('');}
 function subscribe(event:FormEvent){event.preventDefault();const result=simulateBetaSubscribe({email,locale:'es'},seen.current,failWait);setFailWait(false);if(!result.ok){setWaitError(result.error);return}seen.current.add(result.email);setWaitError('');setWaitDone(true);}
 return <div className="page-beta beta-access-preview" data-beta-preview><div className="eva-inner beta-invitation">
 <header className="beta-opening"><p className="editorial-page-label">EVA · Acceso anticipado</p><h1>Conoce EVA desde el comienzo.</h1><p>Una invitación a entender tu salud con más contexto.</p><p className="editorial-form-note">Estás en una demostración. No se concede acceso privado, se crean cookies de acceso ni se envían correos.</p></header>
 <figure className="beta-photo"><img src="/art/editorial/after-cycling-600.webp" alt="Una pausa y un vaso de agua después de pedalear" width="600" height="448" decoding="async"/><figcaption>Un espacio para conocer. Y seguir con tu día.</figcaption></figure>
 <section className="beta-demo-path" aria-labelledby="beta-demo-heading"><span className="beta-path-label">Ya tienes una invitación</span><h2 id="beta-demo-heading">Entra a conocer EVA.</h2><p>Prueba el acceso con una contraseña ficticia, sin abrir ninguna cuenta.</p>{accessNext?<div className="beta-confirmation" role="status"><h3>Acceso de ejemplo comprobado.</h3><p>La comprobación es local. Tu sesión y tus permisos no han cambiado.</p><a className="eva-button" href={accessNext}>Continuar a la demostración<ArrowRight size={17} aria-hidden="true"/></a><button type="button" className="beta-secondary-link" onClick={()=>setAccessNext('')}>Volver a comprobar</button></div>:<form onSubmit={enter}><label className="eva-field">Contraseña de ejemplo<input type="password" name="password" value={password} onChange={event=>{setPassword(event.target.value);setError('')}} required autoComplete="off" aria-invalid={Boolean(error)} aria-describedby={error?'beta-code-note beta-code-error':'beta-code-note'}/></label><p className="editorial-form-note" id="beta-code-note">Usa <strong>EVA-DEMO</strong>. Es una contraseña pública de prueba; no introduzcas una contraseña personal.</p>{error&&<p role="alert" className="editorial-form-error" id="beta-code-error">{error}</p>}<button className="eva-button">Comprobar acceso de ejemplo<ArrowRight size={17} aria-hidden="true"/></button></form>}<details className="beta-scenarios"><summary>Estados de la demostración</summary><label className="eva-field">Acceso<select value={scenario} onChange={event=>{setScenario(event.target.value as BetaScenario);setAccessNext('');setError('')}}><option value="normal">Configurado</option><option value="unconfigured">Sin configurar · acceso cerrado</option><option value="failure">Fallo al comprobar</option></select></label></details></section>
 <section className="beta-site-path beta-waitlist" aria-labelledby="beta-waitlist-heading"><span className="beta-path-label">Para más adelante</span><h2 id="beta-waitlist-heading">Forma parte del comienzo.</h2><p>Así sería la inscripción para recibir novedades sobre el acceso a EVA.</p>{waitDone?<div className="beta-confirmation" role="status"><h3>Inscripción de ejemplo completada.</h3><p>Esta es también la confirmación cuando un correo ya figura en la lista de ejemplo. No se ha enviado a EVA ni guardado fuera de esta página.</p><button type="button" className="beta-secondary-link" onClick={()=>{setWaitDone(false);requestAnimationFrame(()=>emailRef.current?.focus())}}>Probar otra inscripción</button></div>:<form onSubmit={subscribe}><label className="eva-field">Correo de ejemplo<input ref={emailRef} type="email" name="email" autoComplete="off" placeholder="nombre@example.com" value={email} onChange={event=>{setEmail(event.target.value);setWaitError('')}} required aria-invalid={Boolean(waitError)} aria-describedby={waitError?'beta-wait-note beta-wait-error':'beta-wait-note'}/></label><p className="editorial-form-note" id="beta-wait-note">Usa un correo ficticio. Esta prueba solo lo mantiene en memoria mientras la página está abierta.</p>{waitError&&<p role="alert" id="beta-wait-error" className="editorial-form-error">{waitError}</p>}<button className="eva-button">Simular inscripción<ArrowRight size={17} aria-hidden="true"/></button></form>}<details className="beta-scenarios"><summary>Probar un error y reintentar</summary><label className="beta-test-toggle"><input type="checkbox" checked={failWait} onChange={event=>setFailWait(event.target.checked)}/>Simular un fallo en la próxima inscripción</label></details></section>
 <nav className="beta-useful-links" aria-label="Conoce EVA"><a className="editorial-text-link" href="/es/how-it-works">Conoce cómo funciona<ArrowUpRight size={17} aria-hidden="true"/></a><a className="editorial-text-link" href="/es/science">Cómo leer un resultado<ArrowUpRight size={17} aria-hidden="true"/></a></nav>
 </div></div>;
}
