'use client';

import {useCallback, useEffect, useRef, useState, type FormEvent, type KeyboardEvent} from 'react';
import {ArrowRight, ArrowUpRight, ChevronDown, FileText, Pause, RotateCcw, Send, X} from 'lucide-react';
import {usePreview} from '@/components/preview/PreviewProvider';
import {AppPageHeader, AsyncState, ConfirmationDialog, EmptyState, SourceTag, StatusIndicator} from '@/components/preview/AppPrimitives';
import {canReadReport,hasPaidAccess} from '@/lib/preview/policy';
import {dateLabel, numberLabel} from '@/lib/preview/fixtures';
import type {ChatMessage, PreviewState, Report} from '@/lib/preview/model';
import {selectAssistantEvidence as readyEvidence, assistantEvidenceSummary, type AssistantEvidence as Evidence} from './assistant-evidence';
import {zoneLabels} from '../dashboard/dashboard-reading';

export const assistantCopy={es:{
  eyebrow:'EVA AI / Tus informes',title:'Pregunta sobre tus resultados.',description:'Elige un informe. Consulta sus valores mientras exploras una explicación.',
  preview:'Conversación de ejemplo',notice:'EVA AI ofrece información educativa y puede equivocarse. Esta vista muestra respuestas preparadas; no realiza análisis con IA ni ofrece recomendaciones personales.',
  loading:'Preparando la conversación…',
  access:{title:'Entra para continuar.',body:'La conversación está vinculada a tu cuenta. Inicia una sesión de ejemplo para explorarla.',action:'Entrar a la vista previa'},
  health:{title:'Primero, tu consentimiento de salud.',body:'Revisa el tratamiento de datos de salud antes de utilizar la conversación.',action:'Revisar mi perfil'},
  paywall:{eyebrow:'Ejemplo de acceso con un plan',title:'Explora las explicaciones con IA.',body:'Esta demostración permite probar el acceso con un plan de ejemplo. Las funciones y condiciones del servicio deberán confirmarse antes de contratar.',action:'Comparar planes',secondary:'Volver a mis análisis',features:['Preguntas sobre tus biomarcadores','Lecturas de diferentes fechas','Contexto de actividad y descanso'],inactive:'El acceso de pago de este ejemplo no está activo. Revisa las condiciones de tu plan.'},
  consent:{eyebrow:'Tú decides',title:'Activar las explicaciones con IA.',body:'Esta función utiliza la información de salud que compartes para generar explicaciones. El consentimiento de IA es independiente del consentimiento general de salud.',label:'Quiero activar las explicaciones con IA y autorizo el uso de mis datos de salud para esta función.',detail:'En esta vista solo se registra una elección de ejemplo. Puedes revisar el consentimiento desde el perfil.',action:'Activar en la vista previa',busy:'Guardando elección…',privacy:'Leer la política de privacidad',error:'No se pudo guardar la elección. Vuelve a intentarlo.'},
  empty:{eyebrow:'Empieza por una pregunta',title:'¿Qué te gustaría entender?',body:'Elige una de estas preguntas o escribe la tuya. Todas activan una respuesta de demostración, sin interpretar tu salud real.'},
  starters:[{label:'El conjunto',question:'¿Cómo puedo leer mi último informe?'},{label:'Los intervalos',question:'¿Qué significa estar fuera del intervalo?'},{label:'El tiempo',question:'¿Cómo comparo dos fechas?'},{label:'La vida entre lecturas',question:'¿Qué contexto aportan el sueño y la actividad?'}],
  context:{title:'El informe a mano.',label:'Informe para el ejemplo',none:'Sin informe disponible',noneBody:'Puedes explorar preguntas generales. Sube una analítica cuando quieras trabajar con una lectura.',upload:'Subir una analítica',source:'Origen',sources:{kit:'Kit EVA',upload:'Analítica subida'},available:'Lecturas disponibles',drawer:'Abrir datos del informe',drawerTitle:'Datos que acompañan la lectura.',drawerBody:'Valores de ejemplo del informe seleccionado. Solo aparecen cuando el informe está disponible.',close:'Cerrar datos',openReport:'Abrir el informe',noValues:'Este informe no contiene valores utilizables en la vista previa.',removed:'El informe de esta respuesta ya no está disponible.',changed:'El informe cambió después de este ejemplo. El enlace muestra los valores actuales.',reference:'Intervalo orientativo',unclassified:'Sin clasificación',sourceChip:'Ver datos citados',caption:'Los valores son ejemplos; no son datos reales de tu salud.'},
  ui:{you:'Tú',eva:'EVA AI · respuesta de ejemplo',conversation:'Conversación con EVA AI',older:'Mostrar mensajes anteriores',clear:'Vaciar conversación',composer:'Tu pregunta',placeholder:'Escribe lo que te gustaría entender…',send:'Enviar pregunta de ejemplo',stop:'Detener respuesta',busy:'Preparando el ejemplo…',stream:'Mostrando respuesta preparada…',keyboard:'Intro envía. Mayús + Intro añade una línea.',limit:'Máximo 4.000 caracteres.',emptyError:'Escribe una pregunta para continuar.',tooLong:'La pregunta supera los 4.000 caracteres. Acórtala y vuelve a enviarla.',stopped:'Respuesta detenida. El texto mostrado se ha conservado.',stoppedEmpty:'La respuesta se detuvo antes de mostrar texto.',failed:'No se pudo preparar el ejemplo. Puedes volver a intentarlo.',retry:'Reintentar respuesta',recover:'Continuar el ejemplo',legacyRetry:'Volver a enviar la pregunta',finished:'Respuesta de ejemplo completa.',paused:'Vista interrumpida; puedes continuar el ejemplo.',newQuestion:'Escribir otra pregunta',characters:'caracteres',requestFailed:'El intento de ejemplo ha fallado.',resetTitle:'¿Vaciar esta conversación de ejemplo?',resetBody:'Se eliminarán los mensajes de esta vista previa. Tus informes de ejemplo se conservan.',resetConfirm:'Vaciar conversación',resetDone:'Conversación de ejemplo vaciada.'},
  reply:{intro:'Respuesta preparada para esta demostración. No es un análisis generado de tu salud.',noReport:'Todavía no hay un informe disponible para acompañar este ejemplo. Un biomarcador se lee junto con su unidad, el intervalo del laboratorio, la fecha y el contexto de la muestra.',read:'En el informe de ejemplo del',values:'se muestran estas lecturas:',range:'Estar fuera de un intervalo indica dónde se sitúa el valor respecto a ese intervalo. Por sí solo no establece un diagnóstico. El intervalo del laboratorio y el orientativo de EVA pueden responder a criterios diferentes.',time:'Para comparar fechas, comprueba que se trata del mismo biomarcador y de la misma unidad. Aquí no se infieren causas ni se inventan mediciones entre los informes.',wearable:'El sueño y la actividad pueden aportar contexto a una lectura. Esta demostración no calcula correlaciones ni atribuye un cambio del biomarcador a tus hábitos.',age:'La edad biológica es una estimación educativa diferente de la edad cronológica y de la puntuación de longevidad. Puede no estar disponible cuando faltan datos.',ageValue:'En este informe de ejemplo, la estimación disponible es de',years:'años. Es un dato ilustrativo, no una valoración personal.',general:'Un punto de partida es entender qué mide cada biomarcador, revisar su unidad y consultar el informe de origen. Una cifra aislada no resume tu salud.',advanced:'Los valores de la ficha conservan su unidad. Un intervalo desconocido permanece sin clasificación, y no se convierten unidades automáticamente. Las explicaciones no sustituyen una valoración profesional.',closing:'Puedes abrir los datos citados para volver al valor y a su fecha.'},
}};
const c=assistantCopy.es;
type StoredMessage=ChatMessage&{reportId?:string;sourceVersion?:number;sourceKeys?:string[];requestPrompt?:string;preparedText?:string;sourceValues?:Record<string,{value:number;unit:string}>};
type Running={id:string;text:string;fullText:string;position:number;token:number};
const reportPath=(id:string)=>`/es/labs/${encodeURIComponent(id)}`;
const isFiniteNumber=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value);
function preparedReply(question:string,report:Report|undefined,evidence:Evidence[],literacy:PreviewState['profile']['literacy']):string{
  const normalized=question.toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const paragraphs=[c.reply.intro];
  if(report&&evidence.length){const entries=assistantEvidenceSummary(evidence);paragraphs.push(`${c.reply.read} ${dateLabel(report.date)} ${c.reply.values} ${entries}.`);}else paragraphs.push(c.reply.noReport);
  const body=/sueno|actividad|descanso|wearable/.test(normalized)?c.reply.wearable:/edad|longevidad/.test(normalized)?c.reply.age:/fecha|comparo|tiempo|histori/.test(normalized)?c.reply.time:/rango|intervalo|fuera/.test(normalized)?c.reply.range:c.reply.general;
  paragraphs.push(body);
  if(/edad/.test(normalized)&&report&&isFiniteNumber(report.biologicalAge))paragraphs.push(`${c.reply.ageValue} ${numberLabel(report.biologicalAge)} ${c.reply.years}`);
  if(literacy==='advanced')paragraphs.push(c.reply.advanced);
  if(report&&evidence.length&&literacy!=='simple')paragraphs.push(c.reply.closing);
  return paragraphs.join('\n\n');
}

function EvidenceDrawer({reportId,onClose}:{reportId:string;onClose:()=>void}){
  const {state}=usePreview(),ref=useRef<HTMLDialogElement>(null),report=state.reports.find(item=>item.id===reportId&&canReadReport(item,state.profile.healthConsent));
  const evidence=readyEvidence(state,report);
  useEffect(()=>{const node=ref.current;node?.showModal();return()=>node?.close();},[]);
  return <dialog ref={ref} className="assistant-evidence-dialog" aria-labelledby="assistant-evidence-heading" onCancel={event=>{event.preventDefault();onClose();}}><div className="assistant-drawer-head"><div><p className="eva-kicker">{c.preview}</p><h2 id="assistant-evidence-heading">{c.context.drawerTitle}</h2></div><button type="button" onClick={onClose} aria-label={c.context.close}><X size={20}/></button></div><p>{report?c.context.drawerBody:c.context.removed}</p>{report&&<><div className="assistant-drawer-report"><span>{report.name}</span><span>{dateLabel(report.date)}</span></div><div className="assistant-evidence-list">{evidence.map((item,i)=><article key={item.key} data-report-id={item.reportId} data-zone={item.zone} className={`assistant-data-glass assistant-data-tone-${i%3}`}><div><h3>{item.name}</h3><StatusIndicator status={item.status} label={zoneLabels.es[item.zone]}/></div><p className="assistant-evidence-value">{numberLabel(item.value)}<small>{item.unit}</small></p><p className="assistant-evidence-definition">{item.description}</p><div className="assistant-evidence-foot"><span>{c.context.reference}<strong>{item.range?`${numberLabel(item.range[0])}–${numberLabel(item.range[1])} ${item.unit}`:c.context.unclassified}</strong></span><a href={`/es/biomarker/${encodeURIComponent(item.key)}?report=${encodeURIComponent(report.id)}`} aria-label={`${c.context.sourceChip}: ${item.name}`}><ArrowUpRight size={20}/></a></div></article>)}</div>{!evidence.length&&<p>{c.context.noValues}</p>}<a className="eva-button" href={reportPath(report.id)}>{c.context.openReport}<ArrowRight size={16}/></a></>}</dialog>;
}

export default function AssistantPage(){
  const {state,update,request,hydrated}=usePreview(),stateRef=useRef(state);stateRef.current=state;
  const [draft,setDraft]=useState(''),[error,setError]=useState(''),[visibleCount,setVisibleCount]=useState(8),[selectedId,setSelectedId]=useState(''),[drawerId,setDrawerId]=useState<string|null>(null),[resetOpen,setResetOpen]=useState(false),[consentChecked,setConsentChecked]=useState(false),[consentBusy,setConsentBusy]=useState(false),[consentError,setConsentError]=useState('');
  const [runningId,setRunningId]=useState<string|null>(null),[streamText,setStreamText]=useState(''),[phase,setPhase]=useState<'requesting'|'streaming'|null>(null),[announcement,setAnnouncement]=useState(''),[calm,setCalm]=useState(true);
  const running=useRef<Running|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),generation=useRef(0),composer=useRef<HTMLTextAreaElement>(null),clearButton=useRef<HTMLButtonElement>(null),bottom=useRef<HTMLDivElement>(null);
  const paid=hasPaidAccess(state);
  const allowed=state.session&&state.deletionStatus!=='completed'&&state.profile.healthConsent&&state.profile.aiConsent&&paid;
  const reports=state.reports.filter(report=>canReadReport(report,state.profile.healthConsent)).sort((a,b)=>b.date.localeCompare(a.date));
  const report=selectedId?reports.find(item=>item.id===selectedId):reports[0];
  useEffect(()=>{setSelectedId(new URLSearchParams(window.location.search).get('report')||'');},[]);
  const evidence=readyEvidence(state,report),messages=state.chat as StoredMessage[],visibleMessages=messages.slice(-visibleCount);
  const persist=useCallback((id:string,text:string,status:ChatMessage['status'])=>update(current=>({...current,chat:current.chat.map(message=>message.id===id?{...message,text,status}:message)})),[update]);
  const clearTimer=useCallback(()=>{if(timer.current){clearInterval(timer.current);timer.current=null;}},[]);
  const stop=useCallback(async()=>{const active=running.current;if(!active)return;generation.current++;clearTimer();running.current=null;setRunningId(null);setPhase(null);persist(active.id,active.text,'stopped');setAnnouncement(c.ui.stopped);try{await request('chat.stop',{requestId:active.id});}catch{/* The local reveal has already stopped and its text is retained. */}},[clearTimer,persist,request]);
  useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const sync=()=>setCalm(media.matches);sync();media.addEventListener('change',sync);return()=>media.removeEventListener('change',sync);},[]);
  useEffect(()=>()=>{generation.current++;clearTimer();const active=running.current;if(active)persist(active.id,active.text,'stopped');},[clearTimer,persist]);
  useEffect(()=>{if(!hydrated)return;if(!allowed){generation.current++;clearTimer();const active=running.current;if(active)persist(active.id,active.text,'stopped');running.current=null;setRunningId(null);setPhase(null);setDrawerId(null);}if(!state.session||state.deletionStatus==='completed'){if(state.chat.length)update(current=>({...current,chat:[]}));setDraft('');setConsentChecked(false);}},[allowed,hydrated,state.session,state.deletionStatus,state.chat.length,clearTimer,persist,update]);
  useEffect(()=>{if(!state.profile.aiConsent)setConsentChecked(false);},[state.profile.aiConsent]);
  useEffect(()=>{if(running.current&&!state.chat.some(message=>message.id===running.current?.id)){generation.current++;clearTimer();running.current=null;setRunningId(null);setPhase(null);}},[state.chat.length,clearTimer]);
  async function acceptConsent(){if(!consentChecked||consentBusy)return;setConsentBusy(true);setConsentError('');try{const result=await request('consent.save',{scope:'ai',accepted:true,locale:'es',simulated:true});if(!result.ok){setConsentError(result.message);return;}if(!stateRef.current.session||!stateRef.current.profile.healthConsent)return;update(current=>({...current,profile:{...current.profile,aiConsent:true},lastAction:c.consent.action}));}catch{setConsentError(c.consent.error);}finally{setConsentBusy(false);}}
  function scrollToConversation(){requestAnimationFrame(()=>bottom.current?.scrollIntoView({behavior:calm?'auto':'smooth',block:'end'}));}
  async function performReply(message:StoredMessage,retry=false){
    if(running.current||!allowed)return;
    const token=++generation.current,fullText=message.preparedText||preparedReply(message.requestPrompt||'',report,evidence,state.profile.literacy),partial=fullText.startsWith(message.text)?message.text:'';
    running.current={id:message.id,text:partial,fullText,position:partial.length,token};setRunningId(message.id);setStreamText(partial);setPhase('requesting');setError('');setAnnouncement(c.ui.busy);
    try{
      const result=await request('chat.send',{requestId:message.id,message:message.requestPrompt,reportId:message.reportId,simulated:true,simulateError:!retry&&stateRef.current.scenario==='error'});
      if(token!==generation.current||!running.current)return;
      if(!result.ok){persist(message.id,partial,'error');running.current=null;setRunningId(null);setPhase(null);setAnnouncement(c.ui.requestFailed);return;}
      persist(message.id,fullText,'complete');running.current=null;setRunningId(null);setPhase(null);setAnnouncement(c.ui.finished);
    }catch{if(token===generation.current){clearTimer();persist(message.id,partial,'error');running.current=null;setRunningId(null);setPhase(null);setAnnouncement(c.ui.requestFailed);}}
  }
  function ask(text:string){const question=text.trim();if(!allowed||running.current)return;if(!question){setError(c.ui.emptyError);composer.current?.focus();return;}if(question.length>4000){setError(c.ui.tooLong);return;}
    const user:StoredMessage={id:crypto.randomUUID(),role:'user',text:question,status:'complete'};
    const reply:StoredMessage={id:crypto.randomUUID(),role:'assistant',text:'',status:'stopped',requestPrompt:question,reportId:report?.id,sourceVersion:report?.version,sourceKeys:evidence.slice(0,2).map(item=>item.key),sourceValues:Object.fromEntries(evidence.slice(0,2).map(item=>[item.key,{value:item.value,unit:item.unit}])),preparedText:preparedReply(question,report,evidence,state.profile.literacy)};
    update(current=>({...current,chat:[...current.chat,user,reply]}));setDraft('');setError('');setVisibleCount(count=>count+2);void performReply(reply);scrollToConversation();
  }
  function submit(event:FormEvent){event.preventDefault();ask(draft);}
  function key(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();ask(draft);}}
  function reset(){generation.current++;clearTimer();running.current=null;setRunningId(null);setPhase(null);update(current=>({...current,chat:[],lastAction:c.ui.resetDone}));setResetOpen(false);setDraft('');setVisibleCount(8);setAnnouncement(c.ui.resetDone);composer.current?.focus();}
  const header=<AppPageHeader eyebrow={c.eyebrow} title={c.title} description={c.description}/>;
  if(!hydrated)return <div className="page-assistant">{header}<AsyncState message={c.loading}/></div>;
  if(!state.session||state.deletionStatus==='completed')return <div className="page-assistant">{header}<EmptyState title={c.access.title} description={c.access.body}><a className="eva-button" href={`/es/login?redirect=${encodeURIComponent('/es/eva-ai'+(selectedId?'?report='+encodeURIComponent(selectedId):''))}`}>{c.access.action}<ArrowRight size={17}/></a></EmptyState></div>;
  if(!state.profile.healthConsent)return <div className="page-assistant">{header}<EmptyState title={c.health.title} description={c.health.body}><a className="eva-button" href="/es/profile">{c.health.action}</a></EmptyState></div>;
  if(!paid)return <div className="page-assistant">{header}<section className="assistant-paywall"><div><p className="eva-kicker">{c.paywall.eyebrow}</p><h2>{c.paywall.title}</h2><p>{c.paywall.body}</p>{state.plan!=='free'&&<p>{c.paywall.inactive}</p>}<a className="eva-button" href="/es/pricing">{c.paywall.action}<ArrowRight size={17}/></a><a className="eva-text-link" href="/es/labs">{c.paywall.secondary}</a></div><ol>{c.paywall.features.map((item,i)=><li key={item}><span>0{i+1}</span><p>{item}</p></li>)}</ol></section></div>;
  if(!state.profile.aiConsent)return <div className="page-assistant">{header}<section className="assistant-consent"><p className="eva-kicker">{c.consent.eyebrow}</p><h2>{c.consent.title}</h2><p>{c.consent.body}</p><label><input type="checkbox" checked={consentChecked} onChange={event=>setConsentChecked(event.target.checked)} disabled={consentBusy}/><span>{c.consent.label}</span></label><p className="assistant-fine-copy">{c.consent.detail}</p>{consentError&&<p className="eva-form-error" role="alert">{consentError}</p>}<div><button type="button" className="eva-button" onClick={()=>void acceptConsent()} disabled={!consentChecked||consentBusy}>{consentBusy?c.consent.busy:c.consent.action}<ArrowRight size={17}/></button><a className="eva-text-link" href="/es/legal/privacy">{c.consent.privacy}</a></div></section></div>;
  return <div className="page-assistant">
    {header}<p className="assistant-notice">{c.notice}</p>
    <div className="assistant-workspace"><div className="assistant-main"><div className="assistant-conversation-toolbar"><SourceTag>{c.preview}</SourceTag>{messages.length>0&&<button ref={clearButton} type="button" onClick={()=>setResetOpen(true)} disabled={!!runningId}>{c.ui.clear}<RotateCcw size={13}/></button>}</div>
      {!messages.length?<section className="assistant-empty"><p className="eva-kicker">{c.empty.eyebrow}</p><h2>{c.empty.title}</h2><p>{c.empty.body}</p><div className="assistant-starters">{c.starters.map((item,i)=><button type="button" key={item.label} onClick={()=>ask(item.question)}><span><small>0{i+1} / {item.label}</small><strong>{item.question}</strong></span><ArrowUpRight size={19}/></button>)}</div></section>:<section className="assistant-messages" aria-label={c.ui.conversation}>
        {messages.length>visibleCount&&<button type="button" className="assistant-older" onClick={()=>setVisibleCount(count=>count+8)}>{c.ui.older} ({messages.length-visibleCount})</button>}
        {visibleMessages.map(message=>{const active=message.id===runningId,isAssistant=message.role==='assistant',text=active?streamText:message.text,sourceReport=state.reports.find(item=>item.id===message.reportId&&canReadReport(item,state.profile.healthConsent)),liveSources=readyEvidence(state,sourceReport),changed=(!!sourceReport&&message.sourceVersion!==undefined&&message.sourceVersion!==sourceReport.version)||!!message.sourceValues&&Object.entries(message.sourceValues).some(([key,value])=>{const current=liveSources.find(item=>item.key===key);return !!sourceReport&&(!current||current.value!==value.value||current.unit!==value.unit);});return <article key={message.id} className={`assistant-message assistant-message-${message.role}`} aria-busy={active}><p className="assistant-message-author">{isAssistant?c.ui.eva:c.ui.you}</p><div className="assistant-message-body"><p>{text||(active?c.ui.busy:message.status==='error'?c.ui.failed:c.ui.stoppedEmpty)}</p>{active&&<span className="assistant-stream-label">{phase==='requesting'?c.ui.busy:c.ui.stream}</span>}{isAssistant&&!active&&message.status==='stopped'&&<p className="assistant-message-state">{c.ui.stopped}</p>}{isAssistant&&!active&&message.status==='error'&&text&&<p className="assistant-message-state" role="alert">{c.ui.failed}</p>}{isAssistant&&message.reportId&&<div className="assistant-message-sources">{sourceReport?<button type="button" onClick={()=>setDrawerId(sourceReport.id)}><FileText size={13}/>{c.context.sourceChip} · {dateLabel(sourceReport.date)}<ArrowUpRight size={13}/></button>:<span>{c.context.removed}</span>}</div>}{changed&&<p className="assistant-message-state">{c.context.changed}</p>}{isAssistant&&!active&&(message.status==='stopped'||message.status==='error')&&<button type="button" className="assistant-recover" onClick={()=>{if(message.preparedText)void performReply(message,true);else{const index=messages.findIndex(item=>item.id===message.id);const previous=messages.slice(0,index).reverse().find(item=>item.role==='user');if(previous)ask(previous.text);}}} disabled={!!runningId}><RotateCcw size={14}/>{message.preparedText?message.status==='error'?c.ui.retry:c.ui.recover:c.ui.legacyRetry}</button>}</div></article>;})}
      </section>}
      <div ref={bottom} className="assistant-scroll-anchor"/>
      <form className="assistant-composer" onSubmit={submit}><label className="assistant-sr-only" htmlFor="assistant-question">{c.ui.composer}</label><textarea ref={composer} id="assistant-question" value={draft} onChange={event=>{setDraft(event.target.value);if(error)setError('');}} onKeyDown={key} placeholder={c.ui.placeholder} rows={2} maxLength={4000} aria-describedby={`assistant-composer-hint${error?' assistant-composer-error':''}`} aria-invalid={!!error}/><div className="assistant-composer-bottom"><p id="assistant-composer-hint">{c.ui.keyboard}<span>{draft.length} / 4000 {c.ui.characters}</span></p>{runningId?<button type="button" className="assistant-send" onClick={()=>void stop()} aria-label={c.ui.stop}><Pause size={19}/><span>{c.ui.stop}</span></button>:<button type="submit" className="assistant-send" disabled={!draft.trim()} aria-label={c.ui.send}><Send size={18}/><span>{c.ui.send}</span></button>}</div>{error&&<p id="assistant-composer-error" className="eva-form-error" role="alert">{error}</p>}</form>
    </div><aside className="assistant-context"><p className="eva-kicker">{c.context.title}</p><label htmlFor="assistant-report">{c.context.label}</label><div className="assistant-context-select"><select id="assistant-report" value={report?.id||selectedId||''} onChange={event=>setSelectedId(event.target.value)} disabled={!reports.length||!!runningId}>{selectedId&&!report&&<option value={selectedId}>Informe solicitado no disponible</option>}{reports.length?reports.map(item=><option key={item.id} value={item.id}>{dateLabel(item.date)}</option>):<option value="">{c.context.none}</option>}</select><ChevronDown size={15}/></div>{report?<><div className="assistant-context-cover assistant-data-glass"><div className="assistant-context-cover-head"><FileText size={22} aria-hidden="true"/><span>{c.context.sources[report.source]}</span></div><h2>{report.name}</h2><div className="assistant-context-preview">{evidence.slice(0,3).map(item=><div key={item.key}><span>{item.name}</span><strong>{numberLabel(item.value)}<small>{item.unit}</small></strong></div>)}</div><button type="button" onClick={()=>setDrawerId(report.id)}>{c.context.drawer}<ArrowUpRight size={17}/></button></div><p className="assistant-fine-copy">{c.context.caption}</p><a className="eva-text-link" href={reportPath(report.id)}>{c.context.openReport}<ArrowUpRight size={15}/></a></>:<div className="assistant-context-empty"><p>{selectedId?'El informe solicitado no está disponible para esta conversación. Puedes seleccionar otro informe o revisar su estado en Mis análisis.':c.context.noneBody}</p><a className="eva-text-link" href="/es/upload">{c.context.upload}<ArrowRight size={16}/></a></div>}</aside></div>
    <div className="assistant-sr-only" role="status" aria-live="polite" aria-atomic="true">{announcement}</div>
    {drawerId&&<EvidenceDrawer reportId={drawerId} onClose={()=>setDrawerId(null)}/>}
    {resetOpen&&<ConfirmationDialog title={c.ui.resetTitle} description={c.ui.resetBody} confirmLabel={c.ui.resetConfirm} onConfirm={reset} onCancel={()=>{setResetOpen(false);clearButton.current?.focus();}}/>}
  </div>;
}
