'use client';
import type {ReactNode} from 'react';
import {statusLabels,numberLabel} from '@/lib/preview/fixtures';
import type {MarkerStatus} from '@/lib/preview/model';
export function AppPageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="eva-app-page-header"><div>{eyebrow&&<p className="eva-kicker">{eyebrow}</p>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{action}</header>}
export function StatusIndicator({status,label}:{status:MarkerStatus|string;label?:string}){return <span className={`eva-status eva-status-${status}`}><i aria-hidden="true"/>{label||(status==='optimal'?'Dentro del intervalo':statusLabels.es[status as MarkerStatus])||status}</span>}
export function ResultValue({value,unit}:{value:number|string;unit?:string}){return <span className="eva-result-value">{typeof value==='number'?numberLabel(value):value}<small>{unit}</small></span>}
export function EmptyState({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="eva-empty"><span className="eva-empty-mark" aria-hidden="true">∴</span><h2>{title}</h2><p>{description}</p>{children}</div>}
export function AsyncState({message,error=false,children}:{message:string;error?:boolean;children?:ReactNode}){return <div role={error?'alert':'status'} className={`eva-async ${error?'eva-error':''}`}><p>{message}</p>{children}</div>}
export function FieldGroup({title,description,children}:{title:string;description?:string;children:ReactNode}){return <section className="eva-field-group"><div><h2>{title}</h2>{description&&<p>{description}</p>}</div><div className="eva-stack">{children}</div></section>}
export function StepProgress({steps,current}:{steps:string[];current:number}){return <ol className="eva-steps" aria-label="Progreso">{steps.map((s,i)=><li key={s} aria-current={i===current?'step':undefined} data-complete={i<current}><span>{String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol>}
export function ConfirmationDialog({title,description,onConfirm,onCancel,confirmLabel='Confirmar',busy=false}:{title:string;description:string;onConfirm:()=>void;onCancel:()=>void;confirmLabel?:string;busy?:boolean}){return <div className="eva-dialog-backdrop"><div className="eva-dialog" role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Escape')onCancel();if(e.key==='Tab'){const nodes=e.currentTarget.querySelectorAll<HTMLButtonElement>('button');if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes[nodes.length-1]?.focus()}else if(!e.shiftKey&&document.activeElement===nodes[nodes.length-1]){e.preventDefault();nodes[0]?.focus()}}}}><h2>{title}</h2><p>{description}</p><div className="eva-dialog-actions"><button autoFocus className="eva-button eva-button-secondary" onClick={onCancel}>Cancelar</button><button disabled={busy} className="eva-button" onClick={onConfirm}>{busy?'Un momento…':confirmLabel}</button></div></div></div>}
export function SourceTag({children}:{children:ReactNode}){return <span className="eva-source-tag">{children}</span>}
