'use client';
import {useEffect,useState} from 'react';
import type {ReactNode} from 'react';
import {usePathname} from 'next/navigation';
import {LayoutDashboard,ChartNoAxesCombined,Upload,Package,MessageCircle,UserRound,ArrowUpRight,RotateCcw} from 'lucide-react';
import {EvaWordmark} from '@/components/story/EvaWordmark';
import {usePreview} from './PreviewProvider';
import type {Scenario} from '@/lib/preview/model';
const items=[['dashboard','Resumen',LayoutDashboard],['labs','Resultados',ChartNoAxesCombined],['upload','Añadir resultados',Upload],['book','Mi kit',Package],['eva-ai','EVA AI',MessageCircle],['profile','Perfil',UserRound]] as const;
export function AppShell({children,focused=false}:{children:ReactNode;focused?:boolean}){const pathname=usePathname();const{state,reset,hydrated}=usePreview();const[review,setReview]=useState(false);useEffect(()=>{if(!hydrated||!location.hash)return;const frame=requestAnimationFrame(()=>{try{document.getElementById(decodeURIComponent(location.hash.slice(1)))?.scrollIntoView({behavior:'auto',block:'start'})}catch{}});return()=>cancelAnimationFrame(frame)},[hydrated,pathname]);return <div className={`eva-app ${focused?'eva-app-focused':''}`}><a className="skip" href="#app-content">Saltar al contenido</a>{!focused&&<aside className="eva-app-sidebar"><EvaWordmark/><p className="eva-sidebar-label">Tu espacio de salud</p><nav aria-label="Mi EVA">{items.map(([path,label,Icon])=><a key={path} href={`/es/${path}`} aria-current={pathname?.includes('/'+path)?'page':undefined}><Icon size={18} strokeWidth={1.4}/>{label}</a>)}</nav><div className="eva-sidebar-bottom"><p>Tus informes y sus fechas.<br/>Tu próximo paso.</p><a href="/">Descubre EVA <ArrowUpRight size={16}/></a></div></aside>}<div className="eva-app-main"><header className="eva-app-topbar"><a href="/es/dashboard" className="eva-app-mobile-brand" aria-label="EVA, resumen"><span aria-hidden="true"/></a><span className="eva-preview-notice">Vista previa · Datos de ejemplo</span><button className="eva-review-toggle" onClick={()=>setReview(!review)} aria-expanded={review} aria-controls="eva-review-panel">Escenarios</button><a className="eva-avatar" href="/es/profile" aria-label="Tu perfil">{hydrated?state.profile.firstName.slice(0,1):'·'}</a></header>{review&&<div className="eva-review-panel" id="eva-review-panel"><label className="eva-field">Estado de la muestra<select aria-label="Escenario de demostración" value={state.scenario} onChange={e=>reset(e.target.value as Scenario)}><option value="ready">Resultados listos</option><option value="new">Cuenta nueva / gratuita</option><option value="kit">Kit en camino</option><option value="processing">Informe en proceso</option><option value="context">Falta contexto</option><option value="error">Error de extracción</option></select></label><button className="eva-text-link" onClick={()=>reset()}><RotateCcw size={14}/>Restablecer ejemplo</button><p>Todos los cambios se quedan en este navegador. No se conectan cuentas ni se envían datos.</p></div>}<main id="app-content" className="eva-app-content">{children}</main></div>{!focused&&<nav className="eva-app-bottom-nav" aria-label="Navegación móvil">{items.filter(([p])=>p!=='upload').map(([path,label,Icon])=><a key={path} href={`/es/${path}`} aria-current={pathname?.includes('/'+path)?'page':undefined}><Icon size={19} strokeWidth={1.5}/><span>{label}</span></a>)}</nav>}</div>}
