'use client';
import {useEffect,useRef,useState} from 'react';
import {usePreview} from './PreviewProvider';
import {ConfirmationDialog,AsyncState} from './AppPrimitives';
import {invalidateReportEstimates} from '@/lib/preview/policy';
import type {Report} from '@/lib/preview/model';
export default function ReportEditor({report,onClose}:{report:Report;onClose:()=>void}){
 const{state,update,request}=usePreview();const heading=useRef<HTMLHeadingElement>(null);useEffect(()=>{heading.current?.focus({preventScroll:true});heading.current?.scrollIntoView({behavior:'auto',block:'start'})},[report.id]);const[date,setDate]=useState(report.date),[query,setQuery]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const[values,setValues]=useState<Record<string,{value:string;unit:string}>>(()=>Object.fromEntries(report.markerKeys.flatMap(key=>{const m=state.markers.find(m=>m.key===key);if(!m)return[];const o=report.markerValues?.[key];return[[key,{value:String(o?.value??(report.id==='demo-marzo'?(m.history[1]??''):report.id==='demo-junio'?m.value:'')),unit:o?.unit??m.unit}]]})));
 async function save(e:React.FormEvent){e.preventDefault();if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||date>new Date().toISOString().slice(0,10)){setNote('Indica una fecha de extracción válida, sin días futuros.');return}const entries=Object.entries(values);if(entries.some(([,v])=>!v.value.trim()||!Number.isFinite(Number(v.value.replace(',','.')))||Number(v.value.replace(',','.'))<0||!v.unit.trim())){setNote('Revisa los valores: deben ser números positivos o cero, con su unidad.');return}setBusy(true);const result=await request('report.save',{reportId:report.id,collectionDate:date,markerValues:values});setBusy(false);if(!result.ok){setNote(result.message);return}update(s=>({...s,reports:s.reports.map(r=>r.id===report.id?invalidateReportEstimates({...r,date,markerValues:Object.fromEntries(entries.map(([k,v])=>[k,{value:Number(v.value.replace(',','.')),unit:v.unit.trim()}])),biologicalAge:null,longevityScore:null}):r)}));setNote('Cambios guardados en este informe de ejemplo. El informe y sus estimaciones quedan pendientes de actualizar; los demás informes conservan sus valores.');}
 async function remove(){setBusy(true);const result=await request('report.delete',{reportId:report.id});setBusy(false);if(!result.ok){setNote(result.message);return}update(s=>({...s,reports:s.reports.filter(r=>r.id!==report.id)}));onClose();}
 if(!state.session||!state.profile.healthConsent||state.deletionStatus==='completed')return <AsyncState message="La revisión requiere una sesión y permiso para mostrar datos de salud."/>;return <section id={`report-editor-${report.id}`} className="archive-editor" aria-label="Revisión de datos"><div className="archive-editor-title"><div><p className="eva-kicker">INFORME SELECCIONADO</p><h2 ref={heading} tabIndex={-1}>{report.name}</h2></div><button className="eva-text-link" onClick={onClose}>Cerrar revisión</button></div>{note&&<p role="status" className="eva-note">{note}</p>}<form onSubmit={save}><div className="archive-tools"><label className="eva-field">Fecha de extracción<input type="date" value={date} onInput={e=>setDate(e.currentTarget.value)} onChange={e=>setDate(e.target.value)} required/></label><label className="eva-field">Buscar biomarcador<input value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="archive-value-list">{Object.entries(values).filter(([key])=>(state.markers.find(m=>m.key===key)?.name||key).toLowerCase().includes(query.toLowerCase())).map(([key,v])=><div key={key}><strong>{state.markers.find(m=>m.key===key)?.name||key}</strong><label className="eva-field">Valor<input inputMode="decimal" value={v.value} onChange={e=>setValues({...values,[key]:{...v,value:e.target.value}})} aria-label={`Valor de ${key}`}/></label><label className="eva-field">Unidad<input value={v.unit} onChange={e=>setValues({...values,[key]:{...v,unit:e.target.value}})} aria-label={`Unidad de ${key}`}/></label></div>)}</div><p className="eva-note">Copia el valor y la unidad tal como aparecen en el informe. Cambiar una unidad no convierte automáticamente el resultado.</p><div className="archive-editor-actions"><button className="eva-button" disabled={busy}>{busy?'Guardando…':'Guardar cambios de ejemplo'}</button><button type="button" className="eva-text-link" onClick={()=>setConfirm(true)}>Eliminar informe de ejemplo</button></div></form>{confirm&&<ConfirmationDialog title="¿Eliminar este informe de ejemplo?" description="El informe y sus lecturas dejarán de estar disponibles en esta vista previa. Puedes cancelar o recuperar los datos iniciales desde Escenarios. No afecta a información real." onCancel={()=>setConfirm(false)} onConfirm={remove} busy={busy} confirmLabel="Eliminar ejemplo"/>}</section>
}
